Ugly.AtisStatics = {}
Ugly.AtisStatics["ATIS Mozdok"] = {}
Ugly.AtisStatics["ATIS Mozdok"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Mozdok"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Mozdok"]["y"] = 835129.25
Ugly.AtisStatics["ATIS Mozdok"]["x"] = -83958.40625
Ugly.AtisStatics["ATIS Mozdok"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Mozdok"]["heading"] = 4.555309243523
Ugly.AtisStatics["ATIS Mozdok"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Mozdok"]["name"] = "ATIS Mozdok"
Ugly.AtisStatics["ATIS Mozdok"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Mozdok"]["dead"] = false
Ugly.AtisStatics["ATIS Krasnodar-Center"] = {}
Ugly.AtisStatics["ATIS Krasnodar-Center"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Krasnodar-Center"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Krasnodar-Center"]["y"] = 367821.9375
Ugly.AtisStatics["ATIS Krasnodar-Center"]["x"] = 11027.486328125
Ugly.AtisStatics["ATIS Krasnodar-Center"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Krasnodar-Center"]["heading"] = 6.2657318130675
Ugly.AtisStatics["ATIS Krasnodar-Center"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Krasnodar-Center"]["name"] = "ATIS Krasnodar-Center"
Ugly.AtisStatics["ATIS Krasnodar-Center"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Krasnodar-Center"]["dead"] = false
Ugly.AtisStatics["ATIS Sukhumi-Babushara"] = {}
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["y"] = 563717.8125
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["x"] = -219676.0625
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["heading"] = 3.0543263631973
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["name"] = "ATIS Sukhumi-Babushara"
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["dead"] = false
Ugly.AtisStatics["ATIS Maykop-Khanskaya"] = {}
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["y"] = 457873.125
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["x"] = -27874.431640625
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["heading"] = 5.0440016426324
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["name"] = "ATIS Maykop-Khanskaya"
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["dead"] = false
Ugly.AtisStatics["ATIS Gudauta"] = {}
Ugly.AtisStatics["ATIS Gudauta"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Gudauta"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Gudauta"]["y"] = 515909.65625
Ugly.AtisStatics["ATIS Gudauta"]["x"] = -196307.609375
Ugly.AtisStatics["ATIS Gudauta"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Gudauta"]["heading"] = 1.3788102314818
Ugly.AtisStatics["ATIS Gudauta"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Gudauta"]["name"] = "ATIS Gudauta"
Ugly.AtisStatics["ATIS Gudauta"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Gudauta"]["dead"] = false
Ugly.AtisStatics["ATIS Batumi"] = {}
Ugly.AtisStatics["ATIS Batumi"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Batumi"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Batumi"]["y"] = 618278.0625
Ugly.AtisStatics["ATIS Batumi"]["x"] = -355994.78125
Ugly.AtisStatics["ATIS Batumi"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Batumi"]["heading"] = 5.6897735744878
Ugly.AtisStatics["ATIS Batumi"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Batumi"]["name"] = "ATIS Batumi"
Ugly.AtisStatics["ATIS Batumi"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Batumi"]["dead"] = false
Ugly.AtisStatics["ATIS Nalchik"] = {}
Ugly.AtisStatics["ATIS Nalchik"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Nalchik"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Nalchik"]["y"] = 760368.1875
Ugly.AtisStatics["ATIS Nalchik"]["x"] = -125526.4765625
Ugly.AtisStatics["ATIS Nalchik"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Nalchik"]["heading"] = 5.6897735744878
Ugly.AtisStatics["ATIS Nalchik"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Nalchik"]["name"] = "ATIS Nalchik"
Ugly.AtisStatics["ATIS Nalchik"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Nalchik"]["dead"] = false
Ugly.AtisStatics["ATIS Soganlug"] = {}
Ugly.AtisStatics["ATIS Soganlug"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Soganlug"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Soganlug"]["y"] = 894205.1875
Ugly.AtisStatics["ATIS Soganlug"]["x"] = -317181.875
Ugly.AtisStatics["ATIS Soganlug"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Soganlug"]["heading"] = 1.675545322808
Ugly.AtisStatics["ATIS Soganlug"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Soganlug"]["name"] = "ATIS Soganlug"
Ugly.AtisStatics["ATIS Soganlug"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Soganlug"]["dead"] = false
Ugly.AtisStatics["ATIS Senaki-Kolkhi"] = {}
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["y"] = 646339.3125
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["x"] = -281390.71875
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["heading"] = 3.8920841443008
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["name"] = "ATIS Senaki-Kolkhi"
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["dead"] = false
Ugly.AtisStatics["ATIS Gelendzhik"] = {}
Ugly.AtisStatics["ATIS Gelendzhik"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Gelendzhik"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Gelendzhik"]["y"] = 298190.84375
Ugly.AtisStatics["ATIS Gelendzhik"]["x"] = -50243.09375
Ugly.AtisStatics["ATIS Gelendzhik"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Gelendzhik"]["heading"] = 0.62831861911703
Ugly.AtisStatics["ATIS Gelendzhik"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Gelendzhik"]["name"] = "ATIS Gelendzhik"
Ugly.AtisStatics["ATIS Gelendzhik"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Gelendzhik"]["dead"] = false
Ugly.AtisStatics["ATIS Vaziani"] = {}
Ugly.AtisStatics["ATIS Vaziani"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Vaziani"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Vaziani"]["y"] = 904161.25
Ugly.AtisStatics["ATIS Vaziani"]["x"] = -319626.34375
Ugly.AtisStatics["ATIS Vaziani"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Vaziani"]["heading"] = 0.76794466032744
Ugly.AtisStatics["ATIS Vaziani"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Vaziani"]["name"] = "ATIS Vaziani"
Ugly.AtisStatics["ATIS Vaziani"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Vaziani"]["dead"] = false
Ugly.AtisStatics["ATIS Sochi-Adler"] = {}
Ugly.AtisStatics["ATIS Sochi-Adler"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sochi-Adler"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sochi-Adler"]["y"] = 461336.5
Ugly.AtisStatics["ATIS Sochi-Adler"]["x"] = -164620.296875
Ugly.AtisStatics["ATIS Sochi-Adler"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sochi-Adler"]["heading"] = 2.6529005100552
Ugly.AtisStatics["ATIS Sochi-Adler"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sochi-Adler"]["name"] = "ATIS Sochi-Adler"
Ugly.AtisStatics["ATIS Sochi-Adler"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sochi-Adler"]["dead"] = false
Ugly.AtisStatics["ATIS Kobuleti"] = {}
Ugly.AtisStatics["ATIS Kobuleti"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kobuleti"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kobuleti"]["y"] = 636647.125
Ugly.AtisStatics["ATIS Kobuleti"]["x"] = -317259.28125
Ugly.AtisStatics["ATIS Kobuleti"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kobuleti"]["heading"] = 4.3633232644329
Ugly.AtisStatics["ATIS Kobuleti"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kobuleti"]["name"] = "ATIS Kobuleti"
Ugly.AtisStatics["ATIS Kobuleti"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kobuleti"]["dead"] = false
Ugly.AtisStatics["ATIS Novorossiysk"] = {}
Ugly.AtisStatics["ATIS Novorossiysk"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Novorossiysk"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Novorossiysk"]["y"] = 279314.53125
Ugly.AtisStatics["ATIS Novorossiysk"]["x"] = -40217.9140625
Ugly.AtisStatics["ATIS Novorossiysk"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Novorossiysk"]["heading"] = 2.6878071650875
Ugly.AtisStatics["ATIS Novorossiysk"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Novorossiysk"]["name"] = "ATIS Novorossiysk"
Ugly.AtisStatics["ATIS Novorossiysk"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Novorossiysk"]["dead"] = false
Ugly.AtisStatics["ATIS Anapa-Vityazevo"] = {}
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["y"] = 242350.765625
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["x"] = -5558.6787109375
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["heading"] = 3.3161256972962
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["name"] = "ATIS Anapa-Vityazevo"
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["dead"] = false
Ugly.AtisStatics["ATIS Krymsk"] = {}
Ugly.AtisStatics["ATIS Krymsk"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Krymsk"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Krymsk"]["y"] = 294748.625
Ugly.AtisStatics["ATIS Krymsk"]["x"] = -6770.953125
Ugly.AtisStatics["ATIS Krymsk"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Krymsk"]["heading"] = 0.68067815815167
Ugly.AtisStatics["ATIS Krymsk"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Krymsk"]["name"] = "ATIS Krymsk"
Ugly.AtisStatics["ATIS Krymsk"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Krymsk"]["dead"] = false
Ugly.AtisStatics["ATIS Kutaisi"] = {}
Ugly.AtisStatics["ATIS Kutaisi"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kutaisi"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kutaisi"]["y"] = 682961.1875
Ugly.AtisStatics["ATIS Kutaisi"]["x"] = -284446.6875
Ugly.AtisStatics["ATIS Kutaisi"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kutaisi"]["heading"] = 3.9269908169872
Ugly.AtisStatics["ATIS Kutaisi"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kutaisi"]["name"] = "ATIS Kutaisi"
Ugly.AtisStatics["ATIS Kutaisi"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kutaisi"]["dead"] = false
Ugly.AtisStatics["ATIS Mineralnye Vody"] = {}
Ugly.AtisStatics["ATIS Mineralnye Vody"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Mineralnye Vody"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Mineralnye Vody"]["y"] = 706277.625
Ugly.AtisStatics["ATIS Mineralnye Vody"]["x"] = -52001.62890625
Ugly.AtisStatics["ATIS Mineralnye Vody"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Mineralnye Vody"]["heading"] = 0.4363324999791
Ugly.AtisStatics["ATIS Mineralnye Vody"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Mineralnye Vody"]["name"] = "ATIS Mineralnye Vody"
Ugly.AtisStatics["ATIS Mineralnye Vody"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Mineralnye Vody"]["dead"] = false
Ugly.AtisStatics["ATIS Beslan"] = {}
Ugly.AtisStatics["ATIS Beslan"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Beslan"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Beslan"]["y"] = 843628.6875
Ugly.AtisStatics["ATIS Beslan"]["x"] = -148936.890625
Ugly.AtisStatics["ATIS Beslan"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Beslan"]["heading"] = 0.087266268117616
Ugly.AtisStatics["ATIS Beslan"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Beslan"]["name"] = "ATIS Beslan"
Ugly.AtisStatics["ATIS Beslan"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Beslan"]["dead"] = false
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"] = {}
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["y"] = 386457
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["x"] = 8007.7783203125
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["heading"] = 3.8048177655381
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["name"] = "ATIS Krasnodar-Pashkovsky"
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["dead"] = false
Ugly.AtisStatics["ATIS Tbilisi-Lochini"] = {}
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["y"] = 896497.125
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["x"] = -314656.75
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["heading"] = 3.6826446554276
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["name"] = "ATIS Tbilisi-Lochini"
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["dead"] = false
