Ugly.AtisStatics = {}
Ugly.AtisStatics["ATIS Eyn Shemer"] = {}
Ugly.AtisStatics["ATIS Eyn Shemer"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Eyn Shemer"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Eyn Shemer"]["y"] = -92593.5703125
Ugly.AtisStatics["ATIS Eyn Shemer"]["x"] = -283576.9375
Ugly.AtisStatics["ATIS Eyn Shemer"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Eyn Shemer"]["heading"] = 0.19187193830264
Ugly.AtisStatics["ATIS Eyn Shemer"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Eyn Shemer"]["name"] = "ATIS Eyn Shemer"
Ugly.AtisStatics["ATIS Eyn Shemer"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Eyn Shemer"]["dead"] = false
Ugly.AtisStatics["ATIS Marj as Sultan North"] = {}
Ugly.AtisStatics["ATIS Marj as Sultan North"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj as Sultan North"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Marj as Sultan North"]["y"] = 47512.19140625
Ugly.AtisStatics["ATIS Marj as Sultan North"]["x"] = -169970.59375
Ugly.AtisStatics["ATIS Marj as Sultan North"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Marj as Sultan North"]["heading"] = 3.420522376796
Ugly.AtisStatics["ATIS Marj as Sultan North"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj as Sultan North"]["name"] = "ATIS Marj as Sultan North"
Ugly.AtisStatics["ATIS Marj as Sultan North"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Marj as Sultan North"]["dead"] = false
Ugly.AtisStatics["ATIS Minakh"] = {}
Ugly.AtisStatics["ATIS Minakh"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Minakh"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Minakh"]["y"] = 107234.796875
Ugly.AtisStatics["ATIS Minakh"]["x"] = 163518.84375
Ugly.AtisStatics["ATIS Minakh"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Minakh"]["heading"] = 0
Ugly.AtisStatics["ATIS Minakh"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Minakh"]["name"] = "ATIS Minakh"
Ugly.AtisStatics["ATIS Minakh"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Minakh"]["dead"] = false
Ugly.AtisStatics["ATIS Al Qusayr"] = {}
Ugly.AtisStatics["ATIS Al Qusayr"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Qusayr"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al Qusayr"]["y"] = 61372.89453125
Ugly.AtisStatics["ATIS Al Qusayr"]["x"] = -52636.5859375
Ugly.AtisStatics["ATIS Al Qusayr"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al Qusayr"]["heading"] = 1.5358899292969
Ugly.AtisStatics["ATIS Al Qusayr"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Qusayr"]["name"] = "ATIS Al Qusayr"
Ugly.AtisStatics["ATIS Al Qusayr"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al Qusayr"]["dead"] = false
Ugly.AtisStatics["ATIS Bassel Al-Assad"] = {}
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["y"] = 5115.2299804688
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["x"] = 42915.25390625
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["heading"] = 1.536078359291
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["name"] = "ATIS Bassel Al-Assad"
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["dead"] = false
Ugly.AtisStatics["ATIS Abu al-Duhur"] = {}
Ugly.AtisStatics["ATIS Abu al-Duhur"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu al-Duhur"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Abu al-Duhur"]["y"] = 112907.2734375
Ugly.AtisStatics["ATIS Abu al-Duhur"]["x"] = 76198.4453125
Ugly.AtisStatics["ATIS Abu al-Duhur"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Abu al-Duhur"]["heading"] = 0.052359886742702
Ugly.AtisStatics["ATIS Abu al-Duhur"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu al-Duhur"]["name"] = "ATIS Abu al-Duhur"
Ugly.AtisStatics["ATIS Abu al-Duhur"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Abu al-Duhur"]["dead"] = false
Ugly.AtisStatics["ATIS Ramat David"] = {}
Ugly.AtisStatics["ATIS Ramat David"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Ramat David"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Ramat David"]["y"] = -74850.5234375
Ugly.AtisStatics["ATIS Ramat David"]["x"] = -258819.21875
Ugly.AtisStatics["ATIS Ramat David"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Ramat David"]["heading"] = 0.3488051406753
Ugly.AtisStatics["ATIS Ramat David"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Ramat David"]["name"] = "ATIS Ramat David"
Ugly.AtisStatics["ATIS Ramat David"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Ramat David"]["dead"] = false
Ugly.AtisStatics["ATIS Megiddo"] = {}
Ugly.AtisStatics["ATIS Megiddo"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Megiddo"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Megiddo"]["y"] = -70515.890625
Ugly.AtisStatics["ATIS Megiddo"]["x"] = -267337.625
Ugly.AtisStatics["ATIS Megiddo"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Megiddo"]["heading"] = 1.0297444885971
Ugly.AtisStatics["ATIS Megiddo"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Megiddo"]["name"] = "ATIS Megiddo"
Ugly.AtisStatics["ATIS Megiddo"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Megiddo"]["dead"] = false
Ugly.AtisStatics["ATIS Rayak"] = {}
Ugly.AtisStatics["ATIS Rayak"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Rayak"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Rayak"]["y"] = 4621.9892578125
Ugly.AtisStatics["ATIS Rayak"]["x"] = -130044.890625
Ugly.AtisStatics["ATIS Rayak"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Rayak"]["heading"] = 5.5149402209806
Ugly.AtisStatics["ATIS Rayak"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Rayak"]["name"] = "ATIS Rayak"
Ugly.AtisStatics["ATIS Rayak"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Rayak"]["dead"] = false
Ugly.AtisStatics["ATIS Tabqa"] = {}
Ugly.AtisStatics["ATIS Tabqa"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tabqa"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tabqa"]["y"] = 244618.578125
Ugly.AtisStatics["ATIS Tabqa"]["x"] = 77263.4921875
Ugly.AtisStatics["ATIS Tabqa"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tabqa"]["heading"] = 3.1938433755542
Ugly.AtisStatics["ATIS Tabqa"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tabqa"]["name"] = "ATIS Tabqa"
Ugly.AtisStatics["ATIS Tabqa"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tabqa"]["dead"] = false
Ugly.AtisStatics["ATIS Aleppo"] = {}
Ugly.AtisStatics["ATIS Aleppo"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Aleppo"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Aleppo"]["y"] = 123138.6328125
Ugly.AtisStatics["ATIS Aleppo"]["x"] = 125979.890625
Ugly.AtisStatics["ATIS Aleppo"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Aleppo"]["heading"] = 3.3335788919752
Ugly.AtisStatics["ATIS Aleppo"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Aleppo"]["name"] = "ATIS Aleppo"
Ugly.AtisStatics["ATIS Aleppo"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Aleppo"]["dead"] = false
Ugly.AtisStatics["ATIS Palmyra"] = {}
Ugly.AtisStatics["ATIS Palmyra"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Palmyra"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Palmyra"]["y"] = 219837.640625
Ugly.AtisStatics["ATIS Palmyra"]["x"] = -55977.69921875
Ugly.AtisStatics["ATIS Palmyra"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Palmyra"]["heading"] = 6.1437447852141
Ugly.AtisStatics["ATIS Palmyra"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Palmyra"]["name"] = "ATIS Palmyra"
Ugly.AtisStatics["ATIS Palmyra"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Palmyra"]["dead"] = false
Ugly.AtisStatics["ATIS Damascus"] = {}
Ugly.AtisStatics["ATIS Damascus"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Damascus"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Damascus"]["y"] = 51510.41015625
Ugly.AtisStatics["ATIS Damascus"]["x"] = -181031.828125
Ugly.AtisStatics["ATIS Damascus"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Damascus"]["heading"] = 0.89011795457893
Ugly.AtisStatics["ATIS Damascus"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Damascus"]["name"] = "ATIS Damascus"
Ugly.AtisStatics["ATIS Damascus"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Damascus"]["dead"] = false
Ugly.AtisStatics["ATIS Wujah Al Hajar"] = {}
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["y"] = -22907.873046875
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["x"] = -81336.203125
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["heading"] = 0.66335778529643
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["name"] = "ATIS Wujah Al Hajar"
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["dead"] = false
Ugly.AtisStatics["ATIS Incirlik"] = {}
Ugly.AtisStatics["ATIS Incirlik"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Incirlik"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Incirlik"]["y"] = -35242.68359375
Ugly.AtisStatics["ATIS Incirlik"]["x"] = 220498.8125
Ugly.AtisStatics["ATIS Incirlik"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Incirlik"]["heading"] = 5.6546382967056
Ugly.AtisStatics["ATIS Incirlik"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Incirlik"]["name"] = "ATIS Incirlik"
Ugly.AtisStatics["ATIS Incirlik"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Incirlik"]["dead"] = false
Ugly.AtisStatics["ATIS Qabr as Sitt"] = {}
Ugly.AtisStatics["ATIS Qabr as Sitt"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Qabr as Sitt"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Qabr as Sitt"]["y"] = 36845.42578125
Ugly.AtisStatics["ATIS Qabr as Sitt"]["x"] = -174585.828125
Ugly.AtisStatics["ATIS Qabr as Sitt"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Qabr as Sitt"]["heading"] = 2.8623457557545
Ugly.AtisStatics["ATIS Qabr as Sitt"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Qabr as Sitt"]["name"] = "ATIS Qabr as Sitt"
Ugly.AtisStatics["ATIS Qabr as Sitt"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Qabr as Sitt"]["dead"] = false
Ugly.AtisStatics["ATIS Khalkhalah"] = {}
Ugly.AtisStatics["ATIS Khalkhalah"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Khalkhalah"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Khalkhalah"]["y"] = 53908.9609375
Ugly.AtisStatics["ATIS Khalkhalah"]["x"] = -217893.0625
Ugly.AtisStatics["ATIS Khalkhalah"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Khalkhalah"]["heading"] = 2.6005444229584
Ugly.AtisStatics["ATIS Khalkhalah"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Khalkhalah"]["name"] = "ATIS Khalkhalah"
Ugly.AtisStatics["ATIS Khalkhalah"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Khalkhalah"]["dead"] = false
Ugly.AtisStatics["ATIS An Nasiriyah"] = {}
Ugly.AtisStatics["ATIS An Nasiriyah"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS An Nasiriyah"]["CountryID"] = 2
Ugly.AtisStatics["ATIS An Nasiriyah"]["y"] = 85961.5546875
Ugly.AtisStatics["ATIS An Nasiriyah"]["x"] = -123461.1796875
Ugly.AtisStatics["ATIS An Nasiriyah"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS An Nasiriyah"]["heading"] = 0.92520967848089
Ugly.AtisStatics["ATIS An Nasiriyah"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS An Nasiriyah"]["name"] = "ATIS An Nasiriyah"
Ugly.AtisStatics["ATIS An Nasiriyah"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS An Nasiriyah"]["dead"] = false
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"] = {}
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["y"] = -41900.05859375
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["x"] = -131084.421875
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["heading"] = 4.6425756836651
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["name"] = "ATIS Beirut-Rafic Hariri"
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["dead"] = false
Ugly.AtisStatics["ATIS Hatay"] = {}
Ugly.AtisStatics["ATIS Hatay"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Hatay"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Hatay"]["y"] = 38783.62890625
Ugly.AtisStatics["ATIS Hatay"]["x"] = 147667.140625
Ugly.AtisStatics["ATIS Hatay"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Hatay"]["heading"] = 2.3911158337648
Ugly.AtisStatics["ATIS Hatay"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Hatay"]["name"] = "ATIS Hatay"
Ugly.AtisStatics["ATIS Hatay"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Hatay"]["dead"] = false
Ugly.AtisStatics["ATIS King Hussein Air College"] = {}
Ugly.AtisStatics["ATIS King Hussein Air College"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS King Hussein Air College"]["CountryID"] = 2
Ugly.AtisStatics["ATIS King Hussein Air College"]["y"] = 24275.162109375
Ugly.AtisStatics["ATIS King Hussein Air College"]["x"] = -295242.4375
Ugly.AtisStatics["ATIS King Hussein Air College"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS King Hussein Air College"]["heading"] = 3.7873645371225
Ugly.AtisStatics["ATIS King Hussein Air College"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS King Hussein Air College"]["name"] = "ATIS King Hussein Air College"
Ugly.AtisStatics["ATIS King Hussein Air College"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS King Hussein Air College"]["dead"] = false
Ugly.AtisStatics["ATIS Rene Mouawad"] = {}
Ugly.AtisStatics["ATIS Rene Mouawad"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Rene Mouawad"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Rene Mouawad"]["y"] = 8537.21875
Ugly.AtisStatics["ATIS Rene Mouawad"]["x"] = -47984.59375
Ugly.AtisStatics["ATIS Rene Mouawad"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Rene Mouawad"]["heading"] = 2.6354473322669
Ugly.AtisStatics["ATIS Rene Mouawad"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Rene Mouawad"]["name"] = "ATIS Rene Mouawad"
Ugly.AtisStatics["ATIS Rene Mouawad"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Rene Mouawad"]["dead"] = false
Ugly.AtisStatics["ATIS Al-Dumayr"] = {}
Ugly.AtisStatics["ATIS Al-Dumayr"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al-Dumayr"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al-Dumayr"]["y"] = 73980.421875
Ugly.AtisStatics["ATIS Al-Dumayr"]["x"] = -158128.75
Ugly.AtisStatics["ATIS Al-Dumayr"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al-Dumayr"]["heading"] = 2.6703537138866
Ugly.AtisStatics["ATIS Al-Dumayr"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al-Dumayr"]["name"] = "ATIS Al-Dumayr"
Ugly.AtisStatics["ATIS Al-Dumayr"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al-Dumayr"]["dead"] = false
Ugly.AtisStatics["ATIS Adana Sakirpasa"] = {}
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["y"] = -47472.37109375
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["x"] = 219514.53125
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["heading"] = 0.1745327103881
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["name"] = "ATIS Adana Sakirpasa"
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["dead"] = false
Ugly.AtisStatics["ATIS Kuweires"] = {}
Ugly.AtisStatics["ATIS Kuweires"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kuweires"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kuweires"]["y"] = 154797.109375
Ugly.AtisStatics["ATIS Kuweires"]["x"] = 125325.4296875
Ugly.AtisStatics["ATIS Kuweires"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kuweires"]["heading"] = 0.19198638471316
Ugly.AtisStatics["ATIS Kuweires"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kuweires"]["name"] = "ATIS Kuweires"
Ugly.AtisStatics["ATIS Kuweires"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kuweires"]["dead"] = false
Ugly.AtisStatics["ATIS Taftanaz"] = {}
Ugly.AtisStatics["ATIS Taftanaz"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Taftanaz"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Taftanaz"]["y"] = 82940.7421875
Ugly.AtisStatics["ATIS Taftanaz"]["x"] = 103798.0859375
Ugly.AtisStatics["ATIS Taftanaz"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Taftanaz"]["heading"] = 3.420845337465
Ugly.AtisStatics["ATIS Taftanaz"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Taftanaz"]["name"] = "ATIS Taftanaz"
Ugly.AtisStatics["ATIS Taftanaz"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Taftanaz"]["dead"] = false
Ugly.AtisStatics["ATIS Marj as Sultan South"] = {}
Ugly.AtisStatics["ATIS Marj as Sultan South"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj as Sultan South"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Marj as Sultan South"]["y"] = 48059.9296875
Ugly.AtisStatics["ATIS Marj as Sultan South"]["x"] = -171793.140625
Ugly.AtisStatics["ATIS Marj as Sultan South"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Marj as Sultan South"]["heading"] = 1.5883580137075
Ugly.AtisStatics["ATIS Marj as Sultan South"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj as Sultan South"]["name"] = "ATIS Marj as Sultan South"
Ugly.AtisStatics["ATIS Marj as Sultan South"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Marj as Sultan South"]["dead"] = false
Ugly.AtisStatics["ATIS Mezzeh"] = {}
Ugly.AtisStatics["ATIS Mezzeh"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Mezzeh"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Mezzeh"]["y"] = 24431.068359375
Ugly.AtisStatics["ATIS Mezzeh"]["x"] = -172015.84375
Ugly.AtisStatics["ATIS Mezzeh"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Mezzeh"]["heading"] = 2.6003416815269
Ugly.AtisStatics["ATIS Mezzeh"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Mezzeh"]["name"] = "ATIS Mezzeh"
Ugly.AtisStatics["ATIS Mezzeh"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Mezzeh"]["dead"] = false
Ugly.AtisStatics["ATIS Haifa"] = {}
Ugly.AtisStatics["ATIS Haifa"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Haifa"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Haifa"]["y"] = -87774.9453125
Ugly.AtisStatics["ATIS Haifa"]["x"] = -242884.625
Ugly.AtisStatics["ATIS Haifa"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Haifa"]["heading"] = 1.291543802647
Ugly.AtisStatics["ATIS Haifa"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Haifa"]["name"] = "ATIS Haifa"
Ugly.AtisStatics["ATIS Haifa"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Haifa"]["dead"] = false
Ugly.AtisStatics["ATIS Marj Ruhayyil"] = {}
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["y"] = 45971.4921875
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["x"] = -193030.84375
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["heading"] = 1.7622398794294
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["name"] = "ATIS Marj Ruhayyil"
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["dead"] = false
Ugly.AtisStatics["ATIS Kiryat Shmona"] = {}
Ugly.AtisStatics["ATIS Kiryat Shmona"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kiryat Shmona"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kiryat Shmona"]["y"] = -35372.94921875
Ugly.AtisStatics["ATIS Kiryat Shmona"]["x"] = -199940.109375
Ugly.AtisStatics["ATIS Kiryat Shmona"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kiryat Shmona"]["heading"] = 2.6703537138866
Ugly.AtisStatics["ATIS Kiryat Shmona"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kiryat Shmona"]["name"] = "ATIS Kiryat Shmona"
Ugly.AtisStatics["ATIS Kiryat Shmona"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kiryat Shmona"]["dead"] = false
Ugly.AtisStatics["ATIS Jirah"] = {}
Ugly.AtisStatics["ATIS Jirah"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Jirah"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Jirah"]["y"] = 188539.140625
Ugly.AtisStatics["ATIS Jirah"]["x"] = 115190.3984375
Ugly.AtisStatics["ATIS Jirah"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Jirah"]["heading"] = 0.19189057387965
Ugly.AtisStatics["ATIS Jirah"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Jirah"]["name"] = "ATIS Jirah"
Ugly.AtisStatics["ATIS Jirah"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Jirah"]["dead"] = false
Ugly.AtisStatics["ATIS Hama"] = {}
Ugly.AtisStatics["ATIS Hama"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Hama"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Hama"]["y"] = 73964.890625
Ugly.AtisStatics["ATIS Hama"]["x"] = 9171.4091796875
Ugly.AtisStatics["ATIS Hama"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Hama"]["heading"] = 2.7227137565031
Ugly.AtisStatics["ATIS Hama"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Hama"]["name"] = "ATIS Hama"
Ugly.AtisStatics["ATIS Hama"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Hama"]["dead"] = false
