Ugly.AtisStatics = {}
Ugly.AtisStatics["ATIS Khasab"] = {}
Ugly.AtisStatics["ATIS Khasab"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Khasab"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Khasab"]["y"] = -463.55447387695
Ugly.AtisStatics["ATIS Khasab"]["x"] = -505.99624633789
Ugly.AtisStatics["ATIS Khasab"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Khasab"]["heading"] = 1.7974785084196
Ugly.AtisStatics["ATIS Khasab"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Khasab"]["name"] = "ATIS Khasab"
Ugly.AtisStatics["ATIS Khasab"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Khasab"]["dead"] = false
Ugly.AtisStatics["ATIS Fujairah Intl1"] = {}
Ugly.AtisStatics["ATIS Fujairah Intl1"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Fujairah Intl1"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Fujairah Intl1"]["y"] = 9001.1533203125
Ugly.AtisStatics["ATIS Fujairah Intl1"]["x"] = -117706.46875
Ugly.AtisStatics["ATIS Fujairah Intl1"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Fujairah Intl1"]["heading"] = 2.0071184895279
Ugly.AtisStatics["ATIS Fujairah Intl1"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Fujairah Intl1"]["name"] = "ATIS Fujairah Intl1"
Ugly.AtisStatics["ATIS Fujairah Intl1"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Fujairah Intl1"]["dead"] = false
Ugly.AtisStatics["ATIS Liwa AFB"] = {}
Ugly.AtisStatics["ATIS Liwa AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Liwa AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Liwa AFB"]["y"] = -248385.046875
Ugly.AtisStatics["ATIS Liwa AFB"]["x"] = -276166.4375
Ugly.AtisStatics["ATIS Liwa AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Liwa AFB"]["heading"] = 0.68067815815167
Ugly.AtisStatics["ATIS Liwa AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Liwa AFB"]["name"] = "ATIS Liwa AFB"
Ugly.AtisStatics["ATIS Liwa AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Liwa AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Al-Bateen"] = {}
Ugly.AtisStatics["ATIS Al-Bateen"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al-Bateen"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al-Bateen"]["y"] = -182632.09375
Ugly.AtisStatics["ATIS Al-Bateen"]["x"] = -190850.3125
Ugly.AtisStatics["ATIS Al-Bateen"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al-Bateen"]["heading"] = 2.2514746526723
Ugly.AtisStatics["ATIS Al-Bateen"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al-Bateen"]["name"] = "ATIS Al-Bateen"
Ugly.AtisStatics["ATIS Al-Bateen"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al-Bateen"]["dead"] = false
Ugly.AtisStatics["ATIS Qeshm Island"] = {}
Ugly.AtisStatics["ATIS Qeshm Island"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Qeshm Island"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Qeshm Island"]["y"] = -33047.28125
Ugly.AtisStatics["ATIS Qeshm Island"]["x"] = 65732.5390625
Ugly.AtisStatics["ATIS Qeshm Island"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Qeshm Island"]["heading"] = 3.316046850378
Ugly.AtisStatics["ATIS Qeshm Island"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Qeshm Island"]["name"] = "ATIS Qeshm Island"
Ugly.AtisStatics["ATIS Qeshm Island"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Qeshm Island"]["dead"] = false
Ugly.AtisStatics["ATIS Sas Al Nakheel"] = {}
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["y"] = -175540.90625
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["x"] = -190454.53125
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["heading"] = 6.0039324349187
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["name"] = "ATIS Sas Al Nakheel"
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["dead"] = false
Ugly.AtisStatics["ATIS Sirri Island"] = {}
Ugly.AtisStatics["ATIS Sirri Island"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sirri Island"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sirri Island"]["y"] = -169809.71875
Ugly.AtisStatics["ATIS Sirri Island"]["x"] = -27921.30859375
Ugly.AtisStatics["ATIS Sirri Island"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sirri Island"]["heading"] = 0.69810228984512
Ugly.AtisStatics["ATIS Sirri Island"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sirri Island"]["name"] = "ATIS Sirri Island"
Ugly.AtisStatics["ATIS Sirri Island"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sirri Island"]["dead"] = false
Ugly.AtisStatics["ATIS Tunb Kochak"] = {}
Ugly.AtisStatics["ATIS Tunb Kochak"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tunb Kochak"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tunb Kochak"]["y"] = -109303.6328125
Ugly.AtisStatics["ATIS Tunb Kochak"]["x"] = 9002.734375
Ugly.AtisStatics["ATIS Tunb Kochak"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tunb Kochak"]["heading"] = 5.9864792716931
Ugly.AtisStatics["ATIS Tunb Kochak"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tunb Kochak"]["name"] = "ATIS Tunb Kochak"
Ugly.AtisStatics["ATIS Tunb Kochak"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tunb Kochak"]["dead"] = false
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"] = {}
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["y"] = -30729.232421875
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["x"] = -60837.3828125
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["heading"] = 2.9321532895007
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["name"] = "ATIS Ras Al Khaimah Intl"
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Kerman"] = {}
Ugly.AtisStatics["ATIS Kerman"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kerman"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kerman"]["y"] = 71954.8984375
Ugly.AtisStatics["ATIS Kerman"]["x"] = 454022.84375
Ugly.AtisStatics["ATIS Kerman"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kerman"]["heading"] = 3.6128316469267
Ugly.AtisStatics["ATIS Kerman"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kerman"]["name"] = "ATIS Kerman"
Ugly.AtisStatics["ATIS Kerman"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kerman"]["dead"] = false
Ugly.AtisStatics["ATIS Abu Musa Island"] = {}
Ugly.AtisStatics["ATIS Abu Musa Island"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu Musa Island"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Abu Musa Island"]["y"] = -121885.7265625
Ugly.AtisStatics["ATIS Abu Musa Island"]["x"] = -31316.880859375
Ugly.AtisStatics["ATIS Abu Musa Island"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Abu Musa Island"]["heading"] = 4.6774825493672
Ugly.AtisStatics["ATIS Abu Musa Island"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu Musa Island"]["name"] = "ATIS Abu Musa Island"
Ugly.AtisStatics["ATIS Abu Musa Island"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Abu Musa Island"]["dead"] = false
Ugly.AtisStatics["ATIS Tunb Island AFB"] = {}
Ugly.AtisStatics["ATIS Tunb Island AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tunb Island AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tunb Island AFB"]["y"] = -92696.96875
Ugly.AtisStatics["ATIS Tunb Island AFB"]["x"] = 10241.896484375
Ugly.AtisStatics["ATIS Tunb Island AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tunb Island AFB"]["heading"] = 0.52359896114991
Ugly.AtisStatics["ATIS Tunb Island AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tunb Island AFB"]["name"] = "ATIS Tunb Island AFB"
Ugly.AtisStatics["ATIS Tunb Island AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tunb Island AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Kish Intl"] = {}
Ugly.AtisStatics["ATIS Kish Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kish Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kish Intl"]["y"] = -224943.328125
Ugly.AtisStatics["ATIS Kish Intl"]["x"] = 43153.81640625
Ugly.AtisStatics["ATIS Kish Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kish Intl"]["heading"] = 3.2276978045644
Ugly.AtisStatics["ATIS Kish Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kish Intl"]["name"] = "ATIS Kish Intl"
Ugly.AtisStatics["ATIS Kish Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kish Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Havadarya"] = {}
Ugly.AtisStatics["ATIS Havadarya"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Havadarya"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Havadarya"]["y"] = -7060.2290039063
Ugly.AtisStatics["ATIS Havadarya"]["x"] = 108938.6640625
Ugly.AtisStatics["ATIS Havadarya"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Havadarya"]["heading"] = 6.2831198714595
Ugly.AtisStatics["ATIS Havadarya"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Havadarya"]["name"] = "ATIS Havadarya"
Ugly.AtisStatics["ATIS Havadarya"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Havadarya"]["dead"] = false
Ugly.AtisStatics["ATIS Al Minhad AFB"] = {}
Ugly.AtisStatics["ATIS Al Minhad AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Minhad AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al Minhad AFB"]["y"] = -87881.5546875
Ugly.AtisStatics["ATIS Al Minhad AFB"]["x"] = -126408.3828125
Ugly.AtisStatics["ATIS Al Minhad AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al Minhad AFB"]["heading"] = 4.1699523230349e-05
Ugly.AtisStatics["ATIS Al Minhad AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Minhad AFB"]["name"] = "ATIS Al Minhad AFB"
Ugly.AtisStatics["ATIS Al Minhad AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al Minhad AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Sir Abu Nuayr"] = {}
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["y"] = -203075.765625
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["x"] = -103056.15625
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["heading"] = 3.3161256972962
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["name"] = "ATIS Sir Abu Nuayr"
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["dead"] = false
Ugly.AtisStatics["ATIS Al Ain Intl"] = {}
Ugly.AtisStatics["ATIS Al Ain Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Ain Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al Ain Intl"]["y"] = -64730.59765625
Ugly.AtisStatics["ATIS Al Ain Intl"]["x"] = -209183.921875
Ugly.AtisStatics["ATIS Al Ain Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al Ain Intl"]["heading"] = 0
Ugly.AtisStatics["ATIS Al Ain Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Ain Intl"]["name"] = "ATIS Al Ain Intl"
Ugly.AtisStatics["ATIS Al Ain Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al Ain Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Dubai Intl"] = {}
Ugly.AtisStatics["ATIS Dubai Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Dubai Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Dubai Intl"]["y"] = -90677.0390625
Ugly.AtisStatics["ATIS Dubai Intl"]["x"] = -100323.2109375
Ugly.AtisStatics["ATIS Dubai Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Dubai Intl"]["heading"] = 0.54105213476778
Ugly.AtisStatics["ATIS Dubai Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Dubai Intl"]["name"] = "ATIS Dubai Intl"
Ugly.AtisStatics["ATIS Dubai Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Dubai Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Bandar Lengeh"] = {}
Ugly.AtisStatics["ATIS Bandar Lengeh"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar Lengeh"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Bandar Lengeh"]["y"] = -140514.171875
Ugly.AtisStatics["ATIS Bandar Lengeh"]["x"] = 41333.52734375
Ugly.AtisStatics["ATIS Bandar Lengeh"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Bandar Lengeh"]["heading"] = 6.1261057857694
Ugly.AtisStatics["ATIS Bandar Lengeh"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar Lengeh"]["name"] = "ATIS Bandar Lengeh"
Ugly.AtisStatics["ATIS Bandar Lengeh"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Bandar Lengeh"]["dead"] = false
Ugly.AtisStatics["ATIS Bandar-e-Jask"] = {}
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["y"] = 154940
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["x"] = -57594.44140625
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["heading"] = 1.9719691152318
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["name"] = "ATIS Bandar-e-Jask"
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["dead"] = false
Ugly.AtisStatics["ATIS Bandar Abbas Intl"] = {}
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["y"] = 13477.2265625
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["x"] = 115189.0390625
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["heading"] = 3.6127993078887
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["name"] = "ATIS Bandar Abbas Intl"
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Jiroft"] = {}
Ugly.AtisStatics["ATIS Jiroft"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Jiroft"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Jiroft"]["y"] = 141675.375
Ugly.AtisStatics["ATIS Jiroft"]["x"] = 283019.625
Ugly.AtisStatics["ATIS Jiroft"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Jiroft"]["heading"] = 3.8088024480253
Ugly.AtisStatics["ATIS Jiroft"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Jiroft"]["name"] = "ATIS Jiroft"
Ugly.AtisStatics["ATIS Jiroft"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Jiroft"]["dead"] = false
Ugly.AtisStatics["ATIS Al Maktoum Intl"] = {}
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["y"] = -108122.125
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["x"] = -141687.21875
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["heading"] = 0.48869211721105
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["name"] = "ATIS Al Maktoum Intl"
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Al Dhafra AFB"] = {}
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["y"] = -174232.484375
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["x"] = -209311.296875
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["heading"] = 5.4628806396425
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["name"] = "ATIS Al Dhafra AFB"
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Sharjah Intl"] = {}
Ugly.AtisStatics["ATIS Sharjah Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sharjah Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sharjah Intl"]["y"] = -74815.4765625
Ugly.AtisStatics["ATIS Sharjah Intl"]["x"] = -92524.7109375
Ugly.AtisStatics["ATIS Sharjah Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sharjah Intl"]["heading"] = 5.2708946146115
Ugly.AtisStatics["ATIS Sharjah Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sharjah Intl"]["name"] = "ATIS Sharjah Intl"
Ugly.AtisStatics["ATIS Sharjah Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sharjah Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Lavan Island"] = {}
Ugly.AtisStatics["ATIS Lavan Island"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Lavan Island"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Lavan Island"]["y"] = -287456.09375
Ugly.AtisStatics["ATIS Lavan Island"]["x"] = 75728.8046875
Ugly.AtisStatics["ATIS Lavan Island"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Lavan Island"]["heading"] = 0.34906563190573
Ugly.AtisStatics["ATIS Lavan Island"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Lavan Island"]["name"] = "ATIS Lavan Island"
Ugly.AtisStatics["ATIS Lavan Island"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Lavan Island"]["dead"] = false
Ugly.AtisStatics["ATIS Shiraz Intl"] = {}
Ugly.AtisStatics["ATIS Shiraz Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Shiraz Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Shiraz Intl"]["y"] = -352967.25
Ugly.AtisStatics["ATIS Shiraz Intl"]["x"] = 382282.125
Ugly.AtisStatics["ATIS Shiraz Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Shiraz Intl"]["heading"] = 3.6302848777646
Ugly.AtisStatics["ATIS Shiraz Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Shiraz Intl"]["name"] = "ATIS Shiraz Intl"
Ugly.AtisStatics["ATIS Shiraz Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Shiraz Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Lar"] = {}
Ugly.AtisStatics["ATIS Lar"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Lar"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Lar"]["y"] = -182522.59375
Ugly.AtisStatics["ATIS Lar"]["x"] = 168489.34375
Ugly.AtisStatics["ATIS Lar"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Lar"]["heading"] = 1.57079631487
Ugly.AtisStatics["ATIS Lar"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Lar"]["name"] = "ATIS Lar"
Ugly.AtisStatics["ATIS Lar"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Lar"]["dead"] = false
Ugly.AtisStatics["ATIS Abu Dhabi Intl"] = {}
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["y"] = -163420.8125
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["x"] = -189042.71875
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["heading"] = 5.7421331724118
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["name"] = "ATIS Abu Dhabi Intl"
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["dead"] = false
