UglyAtisStatics = {}
UglyAtisStatics["ATIS Mozdok"] = {}
UglyAtisStatics["ATIS Mozdok"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Mozdok"]["CountryID"] = 2
UglyAtisStatics["ATIS Mozdok"]["y"] = 835129.25
UglyAtisStatics["ATIS Mozdok"]["x"] = -83958.40625
UglyAtisStatics["ATIS Mozdok"]["CategoryID"] = 3
UglyAtisStatics["ATIS Mozdok"]["heading"] = 4.555309243523
UglyAtisStatics["ATIS Mozdok"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Mozdok"]["name"] = "ATIS Mozdok"
UglyAtisStatics["ATIS Mozdok"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Mozdok"]["dead"] = false
UglyAtisStatics["ATIS Krasnodar-Center"] = {}
UglyAtisStatics["ATIS Krasnodar-Center"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Krasnodar-Center"]["CountryID"] = 2
UglyAtisStatics["ATIS Krasnodar-Center"]["y"] = 367821.9375
UglyAtisStatics["ATIS Krasnodar-Center"]["x"] = 11027.486328125
UglyAtisStatics["ATIS Krasnodar-Center"]["CategoryID"] = 3
UglyAtisStatics["ATIS Krasnodar-Center"]["heading"] = 6.2657318130675
UglyAtisStatics["ATIS Krasnodar-Center"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Krasnodar-Center"]["name"] = "ATIS Krasnodar-Center"
UglyAtisStatics["ATIS Krasnodar-Center"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Krasnodar-Center"]["dead"] = false
UglyAtisStatics["ATIS Sukhumi-Babushara"] = {}
UglyAtisStatics["ATIS Sukhumi-Babushara"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Sukhumi-Babushara"]["CountryID"] = 2
UglyAtisStatics["ATIS Sukhumi-Babushara"]["y"] = 563717.8125
UglyAtisStatics["ATIS Sukhumi-Babushara"]["x"] = -219676.0625
UglyAtisStatics["ATIS Sukhumi-Babushara"]["CategoryID"] = 3
UglyAtisStatics["ATIS Sukhumi-Babushara"]["heading"] = 3.0543263631973
UglyAtisStatics["ATIS Sukhumi-Babushara"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Sukhumi-Babushara"]["name"] = "ATIS Sukhumi-Babushara"
UglyAtisStatics["ATIS Sukhumi-Babushara"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Sukhumi-Babushara"]["dead"] = false
UglyAtisStatics["ATIS Maykop-Khanskaya"] = {}
UglyAtisStatics["ATIS Maykop-Khanskaya"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Maykop-Khanskaya"]["CountryID"] = 2
UglyAtisStatics["ATIS Maykop-Khanskaya"]["y"] = 457873.125
UglyAtisStatics["ATIS Maykop-Khanskaya"]["x"] = -27874.431640625
UglyAtisStatics["ATIS Maykop-Khanskaya"]["CategoryID"] = 3
UglyAtisStatics["ATIS Maykop-Khanskaya"]["heading"] = 5.0440016426324
UglyAtisStatics["ATIS Maykop-Khanskaya"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Maykop-Khanskaya"]["name"] = "ATIS Maykop-Khanskaya"
UglyAtisStatics["ATIS Maykop-Khanskaya"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Maykop-Khanskaya"]["dead"] = false
UglyAtisStatics["ATIS Gudauta"] = {}
UglyAtisStatics["ATIS Gudauta"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Gudauta"]["CountryID"] = 2
UglyAtisStatics["ATIS Gudauta"]["y"] = 515909.65625
UglyAtisStatics["ATIS Gudauta"]["x"] = -196307.609375
UglyAtisStatics["ATIS Gudauta"]["CategoryID"] = 3
UglyAtisStatics["ATIS Gudauta"]["heading"] = 1.3788102314818
UglyAtisStatics["ATIS Gudauta"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Gudauta"]["name"] = "ATIS Gudauta"
UglyAtisStatics["ATIS Gudauta"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Gudauta"]["dead"] = false
UglyAtisStatics["ATIS Batumi"] = {}
UglyAtisStatics["ATIS Batumi"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Batumi"]["CountryID"] = 2
UglyAtisStatics["ATIS Batumi"]["y"] = 618278.0625
UglyAtisStatics["ATIS Batumi"]["x"] = -355994.78125
UglyAtisStatics["ATIS Batumi"]["CategoryID"] = 3
UglyAtisStatics["ATIS Batumi"]["heading"] = 5.6897735744878
UglyAtisStatics["ATIS Batumi"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Batumi"]["name"] = "ATIS Batumi"
UglyAtisStatics["ATIS Batumi"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Batumi"]["dead"] = false
UglyAtisStatics["ATIS Nalchik"] = {}
UglyAtisStatics["ATIS Nalchik"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Nalchik"]["CountryID"] = 2
UglyAtisStatics["ATIS Nalchik"]["y"] = 760368.1875
UglyAtisStatics["ATIS Nalchik"]["x"] = -125526.4765625
UglyAtisStatics["ATIS Nalchik"]["CategoryID"] = 3
UglyAtisStatics["ATIS Nalchik"]["heading"] = 5.6897735744878
UglyAtisStatics["ATIS Nalchik"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Nalchik"]["name"] = "ATIS Nalchik"
UglyAtisStatics["ATIS Nalchik"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Nalchik"]["dead"] = false
UglyAtisStatics["ATIS Soganlug"] = {}
UglyAtisStatics["ATIS Soganlug"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Soganlug"]["CountryID"] = 2
UglyAtisStatics["ATIS Soganlug"]["y"] = 894205.1875
UglyAtisStatics["ATIS Soganlug"]["x"] = -317181.875
UglyAtisStatics["ATIS Soganlug"]["CategoryID"] = 3
UglyAtisStatics["ATIS Soganlug"]["heading"] = 1.675545322808
UglyAtisStatics["ATIS Soganlug"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Soganlug"]["name"] = "ATIS Soganlug"
UglyAtisStatics["ATIS Soganlug"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Soganlug"]["dead"] = false
UglyAtisStatics["ATIS Senaki-Kolkhi"] = {}
UglyAtisStatics["ATIS Senaki-Kolkhi"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Senaki-Kolkhi"]["CountryID"] = 2
UglyAtisStatics["ATIS Senaki-Kolkhi"]["y"] = 646339.3125
UglyAtisStatics["ATIS Senaki-Kolkhi"]["x"] = -281390.71875
UglyAtisStatics["ATIS Senaki-Kolkhi"]["CategoryID"] = 3
UglyAtisStatics["ATIS Senaki-Kolkhi"]["heading"] = 3.8920841443008
UglyAtisStatics["ATIS Senaki-Kolkhi"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Senaki-Kolkhi"]["name"] = "ATIS Senaki-Kolkhi"
UglyAtisStatics["ATIS Senaki-Kolkhi"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Senaki-Kolkhi"]["dead"] = false
UglyAtisStatics["ATIS Gelendzhik"] = {}
UglyAtisStatics["ATIS Gelendzhik"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Gelendzhik"]["CountryID"] = 2
UglyAtisStatics["ATIS Gelendzhik"]["y"] = 298190.84375
UglyAtisStatics["ATIS Gelendzhik"]["x"] = -50243.09375
UglyAtisStatics["ATIS Gelendzhik"]["CategoryID"] = 3
UglyAtisStatics["ATIS Gelendzhik"]["heading"] = 0.62831861911703
UglyAtisStatics["ATIS Gelendzhik"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Gelendzhik"]["name"] = "ATIS Gelendzhik"
UglyAtisStatics["ATIS Gelendzhik"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Gelendzhik"]["dead"] = false
UglyAtisStatics["ATIS Vaziani"] = {}
UglyAtisStatics["ATIS Vaziani"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Vaziani"]["CountryID"] = 2
UglyAtisStatics["ATIS Vaziani"]["y"] = 904161.25
UglyAtisStatics["ATIS Vaziani"]["x"] = -319626.34375
UglyAtisStatics["ATIS Vaziani"]["CategoryID"] = 3
UglyAtisStatics["ATIS Vaziani"]["heading"] = 0.76794466032744
UglyAtisStatics["ATIS Vaziani"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Vaziani"]["name"] = "ATIS Vaziani"
UglyAtisStatics["ATIS Vaziani"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Vaziani"]["dead"] = false
UglyAtisStatics["ATIS Sochi-Adler"] = {}
UglyAtisStatics["ATIS Sochi-Adler"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Sochi-Adler"]["CountryID"] = 2
UglyAtisStatics["ATIS Sochi-Adler"]["y"] = 461336.5
UglyAtisStatics["ATIS Sochi-Adler"]["x"] = -164620.296875
UglyAtisStatics["ATIS Sochi-Adler"]["CategoryID"] = 3
UglyAtisStatics["ATIS Sochi-Adler"]["heading"] = 2.6529005100552
UglyAtisStatics["ATIS Sochi-Adler"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Sochi-Adler"]["name"] = "ATIS Sochi-Adler"
UglyAtisStatics["ATIS Sochi-Adler"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Sochi-Adler"]["dead"] = false
UglyAtisStatics["ATIS Kobuleti"] = {}
UglyAtisStatics["ATIS Kobuleti"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Kobuleti"]["CountryID"] = 2
UglyAtisStatics["ATIS Kobuleti"]["y"] = 636647.125
UglyAtisStatics["ATIS Kobuleti"]["x"] = -317259.28125
UglyAtisStatics["ATIS Kobuleti"]["CategoryID"] = 3
UglyAtisStatics["ATIS Kobuleti"]["heading"] = 4.3633232644329
UglyAtisStatics["ATIS Kobuleti"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Kobuleti"]["name"] = "ATIS Kobuleti"
UglyAtisStatics["ATIS Kobuleti"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Kobuleti"]["dead"] = false
UglyAtisStatics["ATIS Novorossiysk"] = {}
UglyAtisStatics["ATIS Novorossiysk"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Novorossiysk"]["CountryID"] = 2
UglyAtisStatics["ATIS Novorossiysk"]["y"] = 279314.53125
UglyAtisStatics["ATIS Novorossiysk"]["x"] = -40217.9140625
UglyAtisStatics["ATIS Novorossiysk"]["CategoryID"] = 3
UglyAtisStatics["ATIS Novorossiysk"]["heading"] = 2.6878071650875
UglyAtisStatics["ATIS Novorossiysk"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Novorossiysk"]["name"] = "ATIS Novorossiysk"
UglyAtisStatics["ATIS Novorossiysk"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Novorossiysk"]["dead"] = false
UglyAtisStatics["ATIS Anapa-Vityazevo"] = {}
UglyAtisStatics["ATIS Anapa-Vityazevo"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Anapa-Vityazevo"]["CountryID"] = 2
UglyAtisStatics["ATIS Anapa-Vityazevo"]["y"] = 242350.765625
UglyAtisStatics["ATIS Anapa-Vityazevo"]["x"] = -5558.6787109375
UglyAtisStatics["ATIS Anapa-Vityazevo"]["CategoryID"] = 3
UglyAtisStatics["ATIS Anapa-Vityazevo"]["heading"] = 3.3161256972962
UglyAtisStatics["ATIS Anapa-Vityazevo"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Anapa-Vityazevo"]["name"] = "ATIS Anapa-Vityazevo"
UglyAtisStatics["ATIS Anapa-Vityazevo"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Anapa-Vityazevo"]["dead"] = false
UglyAtisStatics["ATIS Krymsk"] = {}
UglyAtisStatics["ATIS Krymsk"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Krymsk"]["CountryID"] = 2
UglyAtisStatics["ATIS Krymsk"]["y"] = 294748.625
UglyAtisStatics["ATIS Krymsk"]["x"] = -6770.953125
UglyAtisStatics["ATIS Krymsk"]["CategoryID"] = 3
UglyAtisStatics["ATIS Krymsk"]["heading"] = 0.68067815815167
UglyAtisStatics["ATIS Krymsk"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Krymsk"]["name"] = "ATIS Krymsk"
UglyAtisStatics["ATIS Krymsk"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Krymsk"]["dead"] = false
UglyAtisStatics["ATIS Kutaisi"] = {}
UglyAtisStatics["ATIS Kutaisi"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Kutaisi"]["CountryID"] = 2
UglyAtisStatics["ATIS Kutaisi"]["y"] = 682961.1875
UglyAtisStatics["ATIS Kutaisi"]["x"] = -284446.6875
UglyAtisStatics["ATIS Kutaisi"]["CategoryID"] = 3
UglyAtisStatics["ATIS Kutaisi"]["heading"] = 3.9269908169872
UglyAtisStatics["ATIS Kutaisi"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Kutaisi"]["name"] = "ATIS Kutaisi"
UglyAtisStatics["ATIS Kutaisi"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Kutaisi"]["dead"] = false
UglyAtisStatics["ATIS Mineralnye Vody"] = {}
UglyAtisStatics["ATIS Mineralnye Vody"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Mineralnye Vody"]["CountryID"] = 2
UglyAtisStatics["ATIS Mineralnye Vody"]["y"] = 706277.625
UglyAtisStatics["ATIS Mineralnye Vody"]["x"] = -52001.62890625
UglyAtisStatics["ATIS Mineralnye Vody"]["CategoryID"] = 3
UglyAtisStatics["ATIS Mineralnye Vody"]["heading"] = 0.4363324999791
UglyAtisStatics["ATIS Mineralnye Vody"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Mineralnye Vody"]["name"] = "ATIS Mineralnye Vody"
UglyAtisStatics["ATIS Mineralnye Vody"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Mineralnye Vody"]["dead"] = false
UglyAtisStatics["ATIS Beslan"] = {}
UglyAtisStatics["ATIS Beslan"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Beslan"]["CountryID"] = 2
UglyAtisStatics["ATIS Beslan"]["y"] = 843628.6875
UglyAtisStatics["ATIS Beslan"]["x"] = -148936.890625
UglyAtisStatics["ATIS Beslan"]["CategoryID"] = 3
UglyAtisStatics["ATIS Beslan"]["heading"] = 0.087266268117616
UglyAtisStatics["ATIS Beslan"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Beslan"]["name"] = "ATIS Beslan"
UglyAtisStatics["ATIS Beslan"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Beslan"]["dead"] = false
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"] = {}
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"]["CountryID"] = 2
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"]["y"] = 386457
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"]["x"] = 8007.7783203125
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"]["CategoryID"] = 3
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"]["heading"] = 3.8048177655381
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"]["name"] = "ATIS Krasnodar-Pashkovsky"
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Krasnodar-Pashkovsky"]["dead"] = false
UglyAtisStatics["ATIS Tbilisi-Lochini"] = {}
UglyAtisStatics["ATIS Tbilisi-Lochini"]["shape_name"] = "UH-1H"
UglyAtisStatics["ATIS Tbilisi-Lochini"]["CountryID"] = 2
UglyAtisStatics["ATIS Tbilisi-Lochini"]["y"] = 896497.125
UglyAtisStatics["ATIS Tbilisi-Lochini"]["x"] = -314656.75
UglyAtisStatics["ATIS Tbilisi-Lochini"]["CategoryID"] = 3
UglyAtisStatics["ATIS Tbilisi-Lochini"]["heading"] = 3.6826446554276
UglyAtisStatics["ATIS Tbilisi-Lochini"]["type"] = "UH-1H"
UglyAtisStatics["ATIS Tbilisi-Lochini"]["name"] = "ATIS Tbilisi-Lochini"
UglyAtisStatics["ATIS Tbilisi-Lochini"]["CoalitionID"] = 2
UglyAtisStatics["ATIS Tbilisi-Lochini"]["dead"] = false
