Ugly.AtisStatics = {}
Ugly.AtisStatics["ATIS Creech AFB"] = {}
Ugly.AtisStatics["ATIS Creech AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Creech AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Creech AFB"]["y"] = -75144.6640625
Ugly.AtisStatics["ATIS Creech AFB"]["x"] = -360826.75
Ugly.AtisStatics["ATIS Creech AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Creech AFB"]["heading"] = 0.034906688000728
Ugly.AtisStatics["ATIS Creech AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Creech AFB"]["name"] = "ATIS Creech AFB"
Ugly.AtisStatics["ATIS Creech AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Creech AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Beatty Airport"] = {}
Ugly.AtisStatics["ATIS Beatty Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Beatty Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Beatty Airport"]["y"] = -174819.171875
Ugly.AtisStatics["ATIS Beatty Airport"]["x"] = -329773.125
Ugly.AtisStatics["ATIS Beatty Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Beatty Airport"]["heading"] = 6.283068830042
Ugly.AtisStatics["ATIS Beatty Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Beatty Airport"]["name"] = "ATIS Beatty Airport"
Ugly.AtisStatics["ATIS Beatty Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Beatty Airport"]["dead"] = false
Ugly.AtisStatics["ATIS North Las Vegas"] = {}
Ugly.AtisStatics["ATIS North Las Vegas"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS North Las Vegas"]["CountryID"] = 2
Ugly.AtisStatics["ATIS North Las Vegas"]["y"] = -31006.939453125
Ugly.AtisStatics["ATIS North Las Vegas"]["x"] = -401114.6875
Ugly.AtisStatics["ATIS North Las Vegas"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS North Las Vegas"]["heading"] = 4.6600288777917
Ugly.AtisStatics["ATIS North Las Vegas"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS North Las Vegas"]["name"] = "ATIS North Las Vegas"
Ugly.AtisStatics["ATIS North Las Vegas"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS North Las Vegas"]["dead"] = false
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"] = {}
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["y"] = -174118.171875
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["x"] = -226227.140625
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["heading"] = 4.345870102994
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["name"] = "ATIS Tonopah Test Range Airfield"
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["dead"] = false
Ugly.AtisStatics["ATIS Boulder City Airport"] = {}
Ugly.AtisStatics["ATIS Boulder City Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Boulder City Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Boulder City Airport"]["y"] = -690.23468017578
Ugly.AtisStatics["ATIS Boulder City Airport"]["x"] = -429615.375
Ugly.AtisStatics["ATIS Boulder City Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Boulder City Airport"]["heading"] = 3.2637217638999
Ugly.AtisStatics["ATIS Boulder City Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Boulder City Airport"]["name"] = "ATIS Boulder City Airport"
Ugly.AtisStatics["ATIS Boulder City Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Boulder City Airport"]["dead"] = false
Ugly.AtisStatics["ATIS Henderson Executive Airport"] = {}
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["y"] = -26202.18359375
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["x"] = -427089.90625
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["heading"] = 1.5707261589031
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["name"] = "ATIS Henderson Executive Airport"
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["dead"] = false
Ugly.AtisStatics["ATIS Lincoln County"] = {}
Ugly.AtisStatics["ATIS Lincoln County"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Lincoln County"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Lincoln County"]["y"] = 33358.01171875
Ugly.AtisStatics["ATIS Lincoln County"]["x"] = -224245.25
Ugly.AtisStatics["ATIS Lincoln County"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Lincoln County"]["heading"] = 0
Ugly.AtisStatics["ATIS Lincoln County"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Lincoln County"]["name"] = "ATIS Lincoln County"
Ugly.AtisStatics["ATIS Lincoln County"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Lincoln County"]["dead"] = false
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"] = {}
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["y"] = -132990.359375
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["x"] = -303460.09375
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["heading"] = 3.3335788919752
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["name"] = "ATIS Pahute Mesa Airstrip"
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["dead"] = false
Ugly.AtisStatics["ATIS Mesquite"] = {}
Ugly.AtisStatics["ATIS Mesquite"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Mesquite"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Mesquite"]["y"] = 68339.1328125
Ugly.AtisStatics["ATIS Mesquite"]["x"] = -329787.46875
Ugly.AtisStatics["ATIS Mesquite"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Mesquite"]["heading"] = 2.0420353998234
Ugly.AtisStatics["ATIS Mesquite"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Mesquite"]["name"] = "ATIS Mesquite"
Ugly.AtisStatics["ATIS Mesquite"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Mesquite"]["dead"] = false
Ugly.AtisStatics["ATIS Echo Bay"] = {}
Ugly.AtisStatics["ATIS Echo Bay"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Echo Bay"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Echo Bay"]["y"] = 33624.1484375
Ugly.AtisStatics["ATIS Echo Bay"]["x"] = -388543.5
Ugly.AtisStatics["ATIS Echo Bay"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Echo Bay"]["heading"] = 3.420460623074
Ugly.AtisStatics["ATIS Echo Bay"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Echo Bay"]["name"] = "ATIS Echo Bay"
Ugly.AtisStatics["ATIS Echo Bay"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Echo Bay"]["dead"] = false
Ugly.AtisStatics["ATIS McCarran International Airport"] = {}
Ugly.AtisStatics["ATIS McCarran International Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS McCarran International Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS McCarran International Airport"]["y"] = -26912.173828125
Ugly.AtisStatics["ATIS McCarran International Airport"]["x"] = -415480.65625
Ugly.AtisStatics["ATIS McCarran International Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS McCarran International Airport"]["heading"] = 4.4344229184584
Ugly.AtisStatics["ATIS McCarran International Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS McCarran International Airport"]["name"] = "ATIS McCarran International Airport"
Ugly.AtisStatics["ATIS McCarran International Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS McCarran International Airport"]["dead"] = false
Ugly.AtisStatics["ATIS Nellis AFB"] = {}
Ugly.AtisStatics["ATIS Nellis AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Nellis AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Nellis AFB"]["y"] = -17124.751953125
Ugly.AtisStatics["ATIS Nellis AFB"]["x"] = -396616.625
Ugly.AtisStatics["ATIS Nellis AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Nellis AFB"]["heading"] = 6.283162673753
Ugly.AtisStatics["ATIS Nellis AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Nellis AFB"]["name"] = "ATIS Nellis AFB"
Ugly.AtisStatics["ATIS Nellis AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Nellis AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Groom Lake AFB"] = {}
Ugly.AtisStatics["ATIS Groom Lake AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Groom Lake AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Groom Lake AFB"]["y"] = -88856.265625
Ugly.AtisStatics["ATIS Groom Lake AFB"]["x"] = -288548.03125
Ugly.AtisStatics["ATIS Groom Lake AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Groom Lake AFB"]["heading"] = 1.500930113699
Ugly.AtisStatics["ATIS Groom Lake AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Groom Lake AFB"]["name"] = "ATIS Groom Lake AFB"
Ugly.AtisStatics["ATIS Groom Lake AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Groom Lake AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Tonopah Airport"] = {}
Ugly.AtisStatics["ATIS Tonopah Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tonopah Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tonopah Airport"]["y"] = -202422.75
Ugly.AtisStatics["ATIS Tonopah Airport"]["x"] = -197205.515625
Ugly.AtisStatics["ATIS Tonopah Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tonopah Airport"]["heading"] = 2.0420353998234
Ugly.AtisStatics["ATIS Tonopah Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tonopah Airport"]["name"] = "ATIS Tonopah Airport"
Ugly.AtisStatics["ATIS Tonopah Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tonopah Airport"]["dead"] = false
Ugly.AtisStatics["ATIS Laughlin Airport"] = {}
Ugly.AtisStatics["ATIS Laughlin Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Laughlin Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Laughlin Airport"]["y"] = 28445.501953125
Ugly.AtisStatics["ATIS Laughlin Airport"]["x"] = -516316.25
Ugly.AtisStatics["ATIS Laughlin Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Laughlin Airport"]["heading"] = 6.2133722376745
Ugly.AtisStatics["ATIS Laughlin Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Laughlin Airport"]["name"] = "ATIS Laughlin Airport"
Ugly.AtisStatics["ATIS Laughlin Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Laughlin Airport"]["dead"] = false
Ugly.AtisStatics["ATIS Mina Airport 3Q0"] = {}
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["y"] = -290250.65625
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["x"] = -160899.25
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["heading"] = 2.0414938150212
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["name"] = "ATIS Mina Airport 3Q0"
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["dead"] = false
Ugly.AtisStatics["ATIS Jean Airport"] = {}
Ugly.AtisStatics["ATIS Jean Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Jean Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Jean Airport"]["y"] = -43028.15625
Ugly.AtisStatics["ATIS Jean Airport"]["x"] = -450145.09375
Ugly.AtisStatics["ATIS Jean Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Jean Airport"]["heading"] = 2.1118481649927
Ugly.AtisStatics["ATIS Jean Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Jean Airport"]["name"] = "ATIS Jean Airport"
Ugly.AtisStatics["ATIS Jean Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Jean Airport"]["dead"] = false
