AtisStaticsPos = {}
AtisStaticsPos["ATIS Mozdok"] = {} ---Caucasus
AtisStaticsPos["ATIS Mozdok"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Mozdok"]["CountryID"] = 2
AtisStaticsPos["ATIS Mozdok"]["y"] = 835129.25
AtisStaticsPos["ATIS Mozdok"]["x"] = -83958.40625
AtisStaticsPos["ATIS Mozdok"]["CategoryID"] = 3
AtisStaticsPos["ATIS Mozdok"]["heading"] = 4.555309243523
AtisStaticsPos["ATIS Mozdok"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Mozdok"]["name"] = "ATIS Mozdok"
AtisStaticsPos["ATIS Mozdok"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Mozdok"]["dead"] = false
AtisStaticsPos["ATIS Krasnodar-Center"] = {}
AtisStaticsPos["ATIS Krasnodar-Center"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Krasnodar-Center"]["CountryID"] = 2
AtisStaticsPos["ATIS Krasnodar-Center"]["y"] = 367821.9375
AtisStaticsPos["ATIS Krasnodar-Center"]["x"] = 11027.486328125
AtisStaticsPos["ATIS Krasnodar-Center"]["CategoryID"] = 3
AtisStaticsPos["ATIS Krasnodar-Center"]["heading"] = 6.2657318130675
AtisStaticsPos["ATIS Krasnodar-Center"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Krasnodar-Center"]["name"] = "ATIS Krasnodar-Center"
AtisStaticsPos["ATIS Krasnodar-Center"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Krasnodar-Center"]["dead"] = false
AtisStaticsPos["ATIS Sukhumi-Babushara"] = {}
AtisStaticsPos["ATIS Sukhumi-Babushara"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Sukhumi-Babushara"]["CountryID"] = 2
AtisStaticsPos["ATIS Sukhumi-Babushara"]["y"] = 563717.8125
AtisStaticsPos["ATIS Sukhumi-Babushara"]["x"] = -219676.0625
AtisStaticsPos["ATIS Sukhumi-Babushara"]["CategoryID"] = 3
AtisStaticsPos["ATIS Sukhumi-Babushara"]["heading"] = 3.0543263631973
AtisStaticsPos["ATIS Sukhumi-Babushara"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Sukhumi-Babushara"]["name"] = "ATIS Sukhumi-Babushara"
AtisStaticsPos["ATIS Sukhumi-Babushara"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Sukhumi-Babushara"]["dead"] = false
AtisStaticsPos["ATIS Maykop-Khanskaya"] = {}
AtisStaticsPos["ATIS Maykop-Khanskaya"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Maykop-Khanskaya"]["CountryID"] = 2
AtisStaticsPos["ATIS Maykop-Khanskaya"]["y"] = 457873.125
AtisStaticsPos["ATIS Maykop-Khanskaya"]["x"] = -27874.431640625
AtisStaticsPos["ATIS Maykop-Khanskaya"]["CategoryID"] = 3
AtisStaticsPos["ATIS Maykop-Khanskaya"]["heading"] = 5.0440016426324
AtisStaticsPos["ATIS Maykop-Khanskaya"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Maykop-Khanskaya"]["name"] = "ATIS Maykop-Khanskaya"
AtisStaticsPos["ATIS Maykop-Khanskaya"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Maykop-Khanskaya"]["dead"] = false
AtisStaticsPos["ATIS Gudauta"] = {}
AtisStaticsPos["ATIS Gudauta"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Gudauta"]["CountryID"] = 2
AtisStaticsPos["ATIS Gudauta"]["y"] = 515909.65625
AtisStaticsPos["ATIS Gudauta"]["x"] = -196307.609375
AtisStaticsPos["ATIS Gudauta"]["CategoryID"] = 3
AtisStaticsPos["ATIS Gudauta"]["heading"] = 1.3788102314818
AtisStaticsPos["ATIS Gudauta"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Gudauta"]["name"] = "ATIS Gudauta"
AtisStaticsPos["ATIS Gudauta"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Gudauta"]["dead"] = false
AtisStaticsPos["ATIS Batumi"] = {}
AtisStaticsPos["ATIS Batumi"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Batumi"]["CountryID"] = 2
AtisStaticsPos["ATIS Batumi"]["y"] = 618278.0625
AtisStaticsPos["ATIS Batumi"]["x"] = -355994.78125
AtisStaticsPos["ATIS Batumi"]["CategoryID"] = 3
AtisStaticsPos["ATIS Batumi"]["heading"] = 5.6897735744878
AtisStaticsPos["ATIS Batumi"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Batumi"]["name"] = "ATIS Batumi"
AtisStaticsPos["ATIS Batumi"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Batumi"]["dead"] = false
AtisStaticsPos["ATIS Nalchik"] = {}
AtisStaticsPos["ATIS Nalchik"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Nalchik"]["CountryID"] = 2
AtisStaticsPos["ATIS Nalchik"]["y"] = 760368.1875
AtisStaticsPos["ATIS Nalchik"]["x"] = -125526.4765625
AtisStaticsPos["ATIS Nalchik"]["CategoryID"] = 3
AtisStaticsPos["ATIS Nalchik"]["heading"] = 5.6897735744878
AtisStaticsPos["ATIS Nalchik"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Nalchik"]["name"] = "ATIS Nalchik"
AtisStaticsPos["ATIS Nalchik"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Nalchik"]["dead"] = false
AtisStaticsPos["ATIS Soganlug"] = {}
AtisStaticsPos["ATIS Soganlug"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Soganlug"]["CountryID"] = 2
AtisStaticsPos["ATIS Soganlug"]["y"] = 894205.1875
AtisStaticsPos["ATIS Soganlug"]["x"] = -317181.875
AtisStaticsPos["ATIS Soganlug"]["CategoryID"] = 3
AtisStaticsPos["ATIS Soganlug"]["heading"] = 1.675545322808
AtisStaticsPos["ATIS Soganlug"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Soganlug"]["name"] = "ATIS Soganlug"
AtisStaticsPos["ATIS Soganlug"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Soganlug"]["dead"] = false
AtisStaticsPos["ATIS Senaki-Kolkhi"] = {}
AtisStaticsPos["ATIS Senaki-Kolkhi"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Senaki-Kolkhi"]["CountryID"] = 2
AtisStaticsPos["ATIS Senaki-Kolkhi"]["y"] = 646339.3125
AtisStaticsPos["ATIS Senaki-Kolkhi"]["x"] = -281390.71875
AtisStaticsPos["ATIS Senaki-Kolkhi"]["CategoryID"] = 3
AtisStaticsPos["ATIS Senaki-Kolkhi"]["heading"] = 3.8920841443008
AtisStaticsPos["ATIS Senaki-Kolkhi"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Senaki-Kolkhi"]["name"] = "ATIS Senaki-Kolkhi"
AtisStaticsPos["ATIS Senaki-Kolkhi"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Senaki-Kolkhi"]["dead"] = false
AtisStaticsPos["ATIS Gelendzhik"] = {}
AtisStaticsPos["ATIS Gelendzhik"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Gelendzhik"]["CountryID"] = 2
AtisStaticsPos["ATIS Gelendzhik"]["y"] = 298190.84375
AtisStaticsPos["ATIS Gelendzhik"]["x"] = -50243.09375
AtisStaticsPos["ATIS Gelendzhik"]["CategoryID"] = 3
AtisStaticsPos["ATIS Gelendzhik"]["heading"] = 0.62831861911703
AtisStaticsPos["ATIS Gelendzhik"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Gelendzhik"]["name"] = "ATIS Gelendzhik"
AtisStaticsPos["ATIS Gelendzhik"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Gelendzhik"]["dead"] = false
AtisStaticsPos["ATIS Vaziani"] = {}
AtisStaticsPos["ATIS Vaziani"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Vaziani"]["CountryID"] = 2
AtisStaticsPos["ATIS Vaziani"]["y"] = 904161.25
AtisStaticsPos["ATIS Vaziani"]["x"] = -319626.34375
AtisStaticsPos["ATIS Vaziani"]["CategoryID"] = 3
AtisStaticsPos["ATIS Vaziani"]["heading"] = 0.76794466032744
AtisStaticsPos["ATIS Vaziani"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Vaziani"]["name"] = "ATIS Vaziani"
AtisStaticsPos["ATIS Vaziani"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Vaziani"]["dead"] = false
AtisStaticsPos["ATIS Sochi-Adler"] = {}
AtisStaticsPos["ATIS Sochi-Adler"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Sochi-Adler"]["CountryID"] = 2
AtisStaticsPos["ATIS Sochi-Adler"]["y"] = 461336.5
AtisStaticsPos["ATIS Sochi-Adler"]["x"] = -164620.296875
AtisStaticsPos["ATIS Sochi-Adler"]["CategoryID"] = 3
AtisStaticsPos["ATIS Sochi-Adler"]["heading"] = 2.6529005100552
AtisStaticsPos["ATIS Sochi-Adler"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Sochi-Adler"]["name"] = "ATIS Sochi-Adler"
AtisStaticsPos["ATIS Sochi-Adler"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Sochi-Adler"]["dead"] = false
AtisStaticsPos["ATIS Kobuleti"] = {}
AtisStaticsPos["ATIS Kobuleti"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Kobuleti"]["CountryID"] = 2
AtisStaticsPos["ATIS Kobuleti"]["y"] = 636647.125
AtisStaticsPos["ATIS Kobuleti"]["x"] = -317259.28125
AtisStaticsPos["ATIS Kobuleti"]["CategoryID"] = 3
AtisStaticsPos["ATIS Kobuleti"]["heading"] = 4.3633232644329
AtisStaticsPos["ATIS Kobuleti"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Kobuleti"]["name"] = "ATIS Kobuleti"
AtisStaticsPos["ATIS Kobuleti"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Kobuleti"]["dead"] = false
AtisStaticsPos["ATIS Novorossiysk"] = {}
AtisStaticsPos["ATIS Novorossiysk"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Novorossiysk"]["CountryID"] = 2
AtisStaticsPos["ATIS Novorossiysk"]["y"] = 279314.53125
AtisStaticsPos["ATIS Novorossiysk"]["x"] = -40217.9140625
AtisStaticsPos["ATIS Novorossiysk"]["CategoryID"] = 3
AtisStaticsPos["ATIS Novorossiysk"]["heading"] = 2.6878071650875
AtisStaticsPos["ATIS Novorossiysk"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Novorossiysk"]["name"] = "ATIS Novorossiysk"
AtisStaticsPos["ATIS Novorossiysk"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Novorossiysk"]["dead"] = false
AtisStaticsPos["ATIS Anapa-Vityazevo"] = {}
AtisStaticsPos["ATIS Anapa-Vityazevo"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Anapa-Vityazevo"]["CountryID"] = 2
AtisStaticsPos["ATIS Anapa-Vityazevo"]["y"] = 242350.765625
AtisStaticsPos["ATIS Anapa-Vityazevo"]["x"] = -5558.6787109375
AtisStaticsPos["ATIS Anapa-Vityazevo"]["CategoryID"] = 3
AtisStaticsPos["ATIS Anapa-Vityazevo"]["heading"] = 3.3161256972962
AtisStaticsPos["ATIS Anapa-Vityazevo"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Anapa-Vityazevo"]["name"] = "ATIS Anapa-Vityazevo"
AtisStaticsPos["ATIS Anapa-Vityazevo"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Anapa-Vityazevo"]["dead"] = false
AtisStaticsPos["ATIS Krymsk"] = {}
AtisStaticsPos["ATIS Krymsk"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Krymsk"]["CountryID"] = 2
AtisStaticsPos["ATIS Krymsk"]["y"] = 294748.625
AtisStaticsPos["ATIS Krymsk"]["x"] = -6770.953125
AtisStaticsPos["ATIS Krymsk"]["CategoryID"] = 3
AtisStaticsPos["ATIS Krymsk"]["heading"] = 0.68067815815167
AtisStaticsPos["ATIS Krymsk"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Krymsk"]["name"] = "ATIS Krymsk"
AtisStaticsPos["ATIS Krymsk"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Krymsk"]["dead"] = false
AtisStaticsPos["ATIS Kutaisi"] = {}
AtisStaticsPos["ATIS Kutaisi"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Kutaisi"]["CountryID"] = 2
AtisStaticsPos["ATIS Kutaisi"]["y"] = 682961.1875
AtisStaticsPos["ATIS Kutaisi"]["x"] = -284446.6875
AtisStaticsPos["ATIS Kutaisi"]["CategoryID"] = 3
AtisStaticsPos["ATIS Kutaisi"]["heading"] = 3.9269908169872
AtisStaticsPos["ATIS Kutaisi"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Kutaisi"]["name"] = "ATIS Kutaisi"
AtisStaticsPos["ATIS Kutaisi"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Kutaisi"]["dead"] = false
AtisStaticsPos["ATIS Mineralnye Vody"] = {}
AtisStaticsPos["ATIS Mineralnye Vody"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Mineralnye Vody"]["CountryID"] = 2
AtisStaticsPos["ATIS Mineralnye Vody"]["y"] = 706277.625
AtisStaticsPos["ATIS Mineralnye Vody"]["x"] = -52001.62890625
AtisStaticsPos["ATIS Mineralnye Vody"]["CategoryID"] = 3
AtisStaticsPos["ATIS Mineralnye Vody"]["heading"] = 0.4363324999791
AtisStaticsPos["ATIS Mineralnye Vody"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Mineralnye Vody"]["name"] = "ATIS Mineralnye Vody"
AtisStaticsPos["ATIS Mineralnye Vody"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Mineralnye Vody"]["dead"] = false
AtisStaticsPos["ATIS Beslan"] = {}
AtisStaticsPos["ATIS Beslan"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Beslan"]["CountryID"] = 2
AtisStaticsPos["ATIS Beslan"]["y"] = 843628.6875
AtisStaticsPos["ATIS Beslan"]["x"] = -148936.890625
AtisStaticsPos["ATIS Beslan"]["CategoryID"] = 3
AtisStaticsPos["ATIS Beslan"]["heading"] = 0.087266268117616
AtisStaticsPos["ATIS Beslan"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Beslan"]["name"] = "ATIS Beslan"
AtisStaticsPos["ATIS Beslan"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Beslan"]["dead"] = false
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"] = {}
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"]["CountryID"] = 2
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"]["y"] = 386457
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"]["x"] = 8007.7783203125
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"]["CategoryID"] = 3
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"]["heading"] = 3.8048177655381
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"]["name"] = "ATIS Krasnodar-Pashkovsky"
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Krasnodar-Pashkovsky"]["dead"] = false
AtisStaticsPos["ATIS Tbilisi-Lochini"] = {}
AtisStaticsPos["ATIS Tbilisi-Lochini"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Tbilisi-Lochini"]["CountryID"] = 2
AtisStaticsPos["ATIS Tbilisi-Lochini"]["y"] = 896497.125
AtisStaticsPos["ATIS Tbilisi-Lochini"]["x"] = -314656.75
AtisStaticsPos["ATIS Tbilisi-Lochini"]["CategoryID"] = 3
AtisStaticsPos["ATIS Tbilisi-Lochini"]["heading"] = 3.6826446554276
AtisStaticsPos["ATIS Tbilisi-Lochini"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Tbilisi-Lochini"]["name"] = "ATIS Tbilisi-Lochini"
AtisStaticsPos["ATIS Tbilisi-Lochini"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Tbilisi-Lochini"]["dead"] = false
AtisStaticsPos["ATIS Khasab"] = {}  ---PG
AtisStaticsPos["ATIS Khasab"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Khasab"]["CountryID"] = 2
AtisStaticsPos["ATIS Khasab"]["y"] = -463.55447387695
AtisStaticsPos["ATIS Khasab"]["x"] = -505.99624633789
AtisStaticsPos["ATIS Khasab"]["CategoryID"] = 3
AtisStaticsPos["ATIS Khasab"]["heading"] = 1.7974785084196
AtisStaticsPos["ATIS Khasab"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Khasab"]["name"] = "ATIS Khasab"
AtisStaticsPos["ATIS Khasab"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Khasab"]["dead"] = false
AtisStaticsPos["ATIS Fujairah Intl1"] = {}
AtisStaticsPos["ATIS Fujairah Intl1"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Fujairah Intl1"]["CountryID"] = 2
AtisStaticsPos["ATIS Fujairah Intl1"]["y"] = 9001.1533203125
AtisStaticsPos["ATIS Fujairah Intl1"]["x"] = -117706.46875
AtisStaticsPos["ATIS Fujairah Intl1"]["CategoryID"] = 3
AtisStaticsPos["ATIS Fujairah Intl1"]["heading"] = 2.0071184895279
AtisStaticsPos["ATIS Fujairah Intl1"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Fujairah Intl1"]["name"] = "ATIS Fujairah Intl1"
AtisStaticsPos["ATIS Fujairah Intl1"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Fujairah Intl1"]["dead"] = false
AtisStaticsPos["ATIS Liwa AFB"] = {}
AtisStaticsPos["ATIS Liwa AFB"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Liwa AFB"]["CountryID"] = 2
AtisStaticsPos["ATIS Liwa AFB"]["y"] = -248385.046875
AtisStaticsPos["ATIS Liwa AFB"]["x"] = -276166.4375
AtisStaticsPos["ATIS Liwa AFB"]["CategoryID"] = 3
AtisStaticsPos["ATIS Liwa AFB"]["heading"] = 0.68067815815167
AtisStaticsPos["ATIS Liwa AFB"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Liwa AFB"]["name"] = "ATIS Liwa AFB"
AtisStaticsPos["ATIS Liwa AFB"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Liwa AFB"]["dead"] = false
AtisStaticsPos["ATIS Al-Bateen"] = {}
AtisStaticsPos["ATIS Al-Bateen"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Al-Bateen"]["CountryID"] = 2
AtisStaticsPos["ATIS Al-Bateen"]["y"] = -182632.09375
AtisStaticsPos["ATIS Al-Bateen"]["x"] = -190850.3125
AtisStaticsPos["ATIS Al-Bateen"]["CategoryID"] = 3
AtisStaticsPos["ATIS Al-Bateen"]["heading"] = 2.2514746526723
AtisStaticsPos["ATIS Al-Bateen"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Al-Bateen"]["name"] = "ATIS Al-Bateen"
AtisStaticsPos["ATIS Al-Bateen"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Al-Bateen"]["dead"] = false
AtisStaticsPos["ATIS Qeshm Island"] = {}
AtisStaticsPos["ATIS Qeshm Island"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Qeshm Island"]["CountryID"] = 2
AtisStaticsPos["ATIS Qeshm Island"]["y"] = -33047.28125
AtisStaticsPos["ATIS Qeshm Island"]["x"] = 65732.5390625
AtisStaticsPos["ATIS Qeshm Island"]["CategoryID"] = 3
AtisStaticsPos["ATIS Qeshm Island"]["heading"] = 3.316046850378
AtisStaticsPos["ATIS Qeshm Island"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Qeshm Island"]["name"] = "ATIS Qeshm Island"
AtisStaticsPos["ATIS Qeshm Island"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Qeshm Island"]["dead"] = false
AtisStaticsPos["ATIS Sas Al Nakheel"] = {}
AtisStaticsPos["ATIS Sas Al Nakheel"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Sas Al Nakheel"]["CountryID"] = 2
AtisStaticsPos["ATIS Sas Al Nakheel"]["y"] = -175540.90625
AtisStaticsPos["ATIS Sas Al Nakheel"]["x"] = -190454.53125
AtisStaticsPos["ATIS Sas Al Nakheel"]["CategoryID"] = 3
AtisStaticsPos["ATIS Sas Al Nakheel"]["heading"] = 6.0039324349187
AtisStaticsPos["ATIS Sas Al Nakheel"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Sas Al Nakheel"]["name"] = "ATIS Sas Al Nakheel"
AtisStaticsPos["ATIS Sas Al Nakheel"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Sas Al Nakheel"]["dead"] = false
AtisStaticsPos["ATIS Sirri Island"] = {}
AtisStaticsPos["ATIS Sirri Island"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Sirri Island"]["CountryID"] = 2
AtisStaticsPos["ATIS Sirri Island"]["y"] = -169809.71875
AtisStaticsPos["ATIS Sirri Island"]["x"] = -27921.30859375
AtisStaticsPos["ATIS Sirri Island"]["CategoryID"] = 3
AtisStaticsPos["ATIS Sirri Island"]["heading"] = 0.69810228984512
AtisStaticsPos["ATIS Sirri Island"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Sirri Island"]["name"] = "ATIS Sirri Island"
AtisStaticsPos["ATIS Sirri Island"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Sirri Island"]["dead"] = false
AtisStaticsPos["ATIS Tunb Kochak"] = {}
AtisStaticsPos["ATIS Tunb Kochak"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Tunb Kochak"]["CountryID"] = 2
AtisStaticsPos["ATIS Tunb Kochak"]["y"] = -109303.6328125
AtisStaticsPos["ATIS Tunb Kochak"]["x"] = 9002.734375
AtisStaticsPos["ATIS Tunb Kochak"]["CategoryID"] = 3
AtisStaticsPos["ATIS Tunb Kochak"]["heading"] = 5.9864792716931
AtisStaticsPos["ATIS Tunb Kochak"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Tunb Kochak"]["name"] = "ATIS Tunb Kochak"
AtisStaticsPos["ATIS Tunb Kochak"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Tunb Kochak"]["dead"] = false
AtisStaticsPos["ATIS Ras Al Khaimah Intl"] = {}
AtisStaticsPos["ATIS Ras Al Khaimah Intl"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Ras Al Khaimah Intl"]["CountryID"] = 2
AtisStaticsPos["ATIS Ras Al Khaimah Intl"]["y"] = -30729.232421875
AtisStaticsPos["ATIS Ras Al Khaimah Intl"]["x"] = -60837.3828125
AtisStaticsPos["ATIS Ras Al Khaimah Intl"]["CategoryID"] = 3
AtisStaticsPos["ATIS Ras Al Khaimah Intl"]["heading"] = 2.9321532895007
AtisStaticsPos["ATIS Ras Al Khaimah Intl"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Ras Al Khaimah Intl"]["name"] = "ATIS Ras Al Khaimah Intl"
AtisStaticsPos["ATIS Ras Al Khaimah Intl"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Ras Al Khaimah Intl"]["dead"] = false
AtisStaticsPos["ATIS Kerman"] = {}
AtisStaticsPos["ATIS Kerman"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Kerman"]["CountryID"] = 2
AtisStaticsPos["ATIS Kerman"]["y"] = 71954.8984375
AtisStaticsPos["ATIS Kerman"]["x"] = 454022.84375
AtisStaticsPos["ATIS Kerman"]["CategoryID"] = 3
AtisStaticsPos["ATIS Kerman"]["heading"] = 3.6128316469267
AtisStaticsPos["ATIS Kerman"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Kerman"]["name"] = "ATIS Kerman"
AtisStaticsPos["ATIS Kerman"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Kerman"]["dead"] = false
AtisStaticsPos["ATIS Abu Musa Island"] = {}
AtisStaticsPos["ATIS Abu Musa Island"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Abu Musa Island"]["CountryID"] = 2
AtisStaticsPos["ATIS Abu Musa Island"]["y"] = -121885.7265625
AtisStaticsPos["ATIS Abu Musa Island"]["x"] = -31316.880859375
AtisStaticsPos["ATIS Abu Musa Island"]["CategoryID"] = 3
AtisStaticsPos["ATIS Abu Musa Island"]["heading"] = 4.6774825493672
AtisStaticsPos["ATIS Abu Musa Island"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Abu Musa Island"]["name"] = "ATIS Abu Musa Island"
AtisStaticsPos["ATIS Abu Musa Island"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Abu Musa Island"]["dead"] = false
AtisStaticsPos["ATIS Tunb Island AFB"] = {}
AtisStaticsPos["ATIS Tunb Island AFB"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Tunb Island AFB"]["CountryID"] = 2
AtisStaticsPos["ATIS Tunb Island AFB"]["y"] = -92696.96875
AtisStaticsPos["ATIS Tunb Island AFB"]["x"] = 10241.896484375
AtisStaticsPos["ATIS Tunb Island AFB"]["CategoryID"] = 3
AtisStaticsPos["ATIS Tunb Island AFB"]["heading"] = 0.52359896114991
AtisStaticsPos["ATIS Tunb Island AFB"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Tunb Island AFB"]["name"] = "ATIS Tunb Island AFB"
AtisStaticsPos["ATIS Tunb Island AFB"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Tunb Island AFB"]["dead"] = false
AtisStaticsPos["ATIS Kish Intl"] = {}
AtisStaticsPos["ATIS Kish Intl"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Kish Intl"]["CountryID"] = 2
AtisStaticsPos["ATIS Kish Intl"]["y"] = -224943.328125
AtisStaticsPos["ATIS Kish Intl"]["x"] = 43153.81640625
AtisStaticsPos["ATIS Kish Intl"]["CategoryID"] = 3
AtisStaticsPos["ATIS Kish Intl"]["heading"] = 3.2276978045644
AtisStaticsPos["ATIS Kish Intl"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Kish Intl"]["name"] = "ATIS Kish Intl"
AtisStaticsPos["ATIS Kish Intl"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Kish Intl"]["dead"] = false
AtisStaticsPos["ATIS Havadarya"] = {}
AtisStaticsPos["ATIS Havadarya"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Havadarya"]["CountryID"] = 2
AtisStaticsPos["ATIS Havadarya"]["y"] = -7060.2290039063
AtisStaticsPos["ATIS Havadarya"]["x"] = 108938.6640625
AtisStaticsPos["ATIS Havadarya"]["CategoryID"] = 3
AtisStaticsPos["ATIS Havadarya"]["heading"] = 6.2831198714595
AtisStaticsPos["ATIS Havadarya"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Havadarya"]["name"] = "ATIS Havadarya"
AtisStaticsPos["ATIS Havadarya"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Havadarya"]["dead"] = false
AtisStaticsPos["ATIS Al Minhad AFB"] = {}
AtisStaticsPos["ATIS Al Minhad AFB"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Al Minhad AFB"]["CountryID"] = 2
AtisStaticsPos["ATIS Al Minhad AFB"]["y"] = -87881.5546875
AtisStaticsPos["ATIS Al Minhad AFB"]["x"] = -126408.3828125
AtisStaticsPos["ATIS Al Minhad AFB"]["CategoryID"] = 3
AtisStaticsPos["ATIS Al Minhad AFB"]["heading"] = 4.1699523230349e-05
AtisStaticsPos["ATIS Al Minhad AFB"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Al Minhad AFB"]["name"] = "ATIS Al Minhad AFB"
AtisStaticsPos["ATIS Al Minhad AFB"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Al Minhad AFB"]["dead"] = false
AtisStaticsPos["ATIS Sir Abu Nuayr"] = {}
AtisStaticsPos["ATIS Sir Abu Nuayr"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Sir Abu Nuayr"]["CountryID"] = 2
AtisStaticsPos["ATIS Sir Abu Nuayr"]["y"] = -203075.765625
AtisStaticsPos["ATIS Sir Abu Nuayr"]["x"] = -103056.15625
AtisStaticsPos["ATIS Sir Abu Nuayr"]["CategoryID"] = 3
AtisStaticsPos["ATIS Sir Abu Nuayr"]["heading"] = 3.3161256972962
AtisStaticsPos["ATIS Sir Abu Nuayr"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Sir Abu Nuayr"]["name"] = "ATIS Sir Abu Nuayr"
AtisStaticsPos["ATIS Sir Abu Nuayr"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Sir Abu Nuayr"]["dead"] = false
AtisStaticsPos["ATIS Al Ain Intl"] = {}
AtisStaticsPos["ATIS Al Ain Intl"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Al Ain Intl"]["CountryID"] = 2
AtisStaticsPos["ATIS Al Ain Intl"]["y"] = -64730.59765625
AtisStaticsPos["ATIS Al Ain Intl"]["x"] = -209183.921875
AtisStaticsPos["ATIS Al Ain Intl"]["CategoryID"] = 3
AtisStaticsPos["ATIS Al Ain Intl"]["heading"] = 0
AtisStaticsPos["ATIS Al Ain Intl"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Al Ain Intl"]["name"] = "ATIS Al Ain Intl"
AtisStaticsPos["ATIS Al Ain Intl"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Al Ain Intl"]["dead"] = false
AtisStaticsPos["ATIS Dubai Intl"] = {}
AtisStaticsPos["ATIS Dubai Intl"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Dubai Intl"]["CountryID"] = 2
AtisStaticsPos["ATIS Dubai Intl"]["y"] = -90677.0390625
AtisStaticsPos["ATIS Dubai Intl"]["x"] = -100323.2109375
AtisStaticsPos["ATIS Dubai Intl"]["CategoryID"] = 3
AtisStaticsPos["ATIS Dubai Intl"]["heading"] = 0.54105213476778
AtisStaticsPos["ATIS Dubai Intl"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Dubai Intl"]["name"] = "ATIS Dubai Intl"
AtisStaticsPos["ATIS Dubai Intl"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Dubai Intl"]["dead"] = false
AtisStaticsPos["ATIS Bandar Lengeh"] = {}
AtisStaticsPos["ATIS Bandar Lengeh"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Bandar Lengeh"]["CountryID"] = 2
AtisStaticsPos["ATIS Bandar Lengeh"]["y"] = -140514.171875
AtisStaticsPos["ATIS Bandar Lengeh"]["x"] = 41333.52734375
AtisStaticsPos["ATIS Bandar Lengeh"]["CategoryID"] = 3
AtisStaticsPos["ATIS Bandar Lengeh"]["heading"] = 6.1261057857694
AtisStaticsPos["ATIS Bandar Lengeh"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Bandar Lengeh"]["name"] = "ATIS Bandar Lengeh"
AtisStaticsPos["ATIS Bandar Lengeh"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Bandar Lengeh"]["dead"] = false
AtisStaticsPos["ATIS Bandar-e-Jask"] = {}
AtisStaticsPos["ATIS Bandar-e-Jask"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Bandar-e-Jask"]["CountryID"] = 2
AtisStaticsPos["ATIS Bandar-e-Jask"]["y"] = 154940
AtisStaticsPos["ATIS Bandar-e-Jask"]["x"] = -57594.44140625
AtisStaticsPos["ATIS Bandar-e-Jask"]["CategoryID"] = 3
AtisStaticsPos["ATIS Bandar-e-Jask"]["heading"] = 1.9719691152318
AtisStaticsPos["ATIS Bandar-e-Jask"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Bandar-e-Jask"]["name"] = "ATIS Bandar-e-Jask"
AtisStaticsPos["ATIS Bandar-e-Jask"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Bandar-e-Jask"]["dead"] = false
AtisStaticsPos["ATIS Bandar Abbas Intl"] = {}
AtisStaticsPos["ATIS Bandar Abbas Intl"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Bandar Abbas Intl"]["CountryID"] = 2
AtisStaticsPos["ATIS Bandar Abbas Intl"]["y"] = 13477.2265625
AtisStaticsPos["ATIS Bandar Abbas Intl"]["x"] = 115189.0390625
AtisStaticsPos["ATIS Bandar Abbas Intl"]["CategoryID"] = 3
AtisStaticsPos["ATIS Bandar Abbas Intl"]["heading"] = 3.6127993078887
AtisStaticsPos["ATIS Bandar Abbas Intl"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Bandar Abbas Intl"]["name"] = "ATIS Bandar Abbas Intl"
AtisStaticsPos["ATIS Bandar Abbas Intl"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Bandar Abbas Intl"]["dead"] = false
AtisStaticsPos["ATIS Jiroft"] = {}
AtisStaticsPos["ATIS Jiroft"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Jiroft"]["CountryID"] = 2
AtisStaticsPos["ATIS Jiroft"]["y"] = 141675.375
AtisStaticsPos["ATIS Jiroft"]["x"] = 283019.625
AtisStaticsPos["ATIS Jiroft"]["CategoryID"] = 3
AtisStaticsPos["ATIS Jiroft"]["heading"] = 3.8088024480253
AtisStaticsPos["ATIS Jiroft"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Jiroft"]["name"] = "ATIS Jiroft"
AtisStaticsPos["ATIS Jiroft"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Jiroft"]["dead"] = false
AtisStaticsPos["ATIS Al Maktoum Intl"] = {}
AtisStaticsPos["ATIS Al Maktoum Intl"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Al Maktoum Intl"]["CountryID"] = 2
AtisStaticsPos["ATIS Al Maktoum Intl"]["y"] = -108122.125
AtisStaticsPos["ATIS Al Maktoum Intl"]["x"] = -141687.21875
AtisStaticsPos["ATIS Al Maktoum Intl"]["CategoryID"] = 3
AtisStaticsPos["ATIS Al Maktoum Intl"]["heading"] = 0.48869211721105
AtisStaticsPos["ATIS Al Maktoum Intl"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Al Maktoum Intl"]["name"] = "ATIS Al Maktoum Intl"
AtisStaticsPos["ATIS Al Maktoum Intl"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Al Maktoum Intl"]["dead"] = false
AtisStaticsPos["ATIS Al Dhafra AFB"] = {}
AtisStaticsPos["ATIS Al Dhafra AFB"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Al Dhafra AFB"]["CountryID"] = 2
AtisStaticsPos["ATIS Al Dhafra AFB"]["y"] = -174232.484375
AtisStaticsPos["ATIS Al Dhafra AFB"]["x"] = -209311.296875
AtisStaticsPos["ATIS Al Dhafra AFB"]["CategoryID"] = 3
AtisStaticsPos["ATIS Al Dhafra AFB"]["heading"] = 5.4628806396425
AtisStaticsPos["ATIS Al Dhafra AFB"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Al Dhafra AFB"]["name"] = "ATIS Al Dhafra AFB"
AtisStaticsPos["ATIS Al Dhafra AFB"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Al Dhafra AFB"]["dead"] = false
AtisStaticsPos["ATIS Sharjah Intl"] = {}
AtisStaticsPos["ATIS Sharjah Intl"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Sharjah Intl"]["CountryID"] = 2
AtisStaticsPos["ATIS Sharjah Intl"]["y"] = -74815.4765625
AtisStaticsPos["ATIS Sharjah Intl"]["x"] = -92524.7109375
AtisStaticsPos["ATIS Sharjah Intl"]["CategoryID"] = 3
AtisStaticsPos["ATIS Sharjah Intl"]["heading"] = 5.2708946146115
AtisStaticsPos["ATIS Sharjah Intl"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Sharjah Intl"]["name"] = "ATIS Sharjah Intl"
AtisStaticsPos["ATIS Sharjah Intl"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Sharjah Intl"]["dead"] = false
AtisStaticsPos["ATIS Lavan Island"] = {}
AtisStaticsPos["ATIS Lavan Island"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Lavan Island"]["CountryID"] = 2
AtisStaticsPos["ATIS Lavan Island"]["y"] = -287456.09375
AtisStaticsPos["ATIS Lavan Island"]["x"] = 75728.8046875
AtisStaticsPos["ATIS Lavan Island"]["CategoryID"] = 3
AtisStaticsPos["ATIS Lavan Island"]["heading"] = 0.34906563190573
AtisStaticsPos["ATIS Lavan Island"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Lavan Island"]["name"] = "ATIS Lavan Island"
AtisStaticsPos["ATIS Lavan Island"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Lavan Island"]["dead"] = false
AtisStaticsPos["ATIS Shiraz Intl"] = {}
AtisStaticsPos["ATIS Shiraz Intl"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Shiraz Intl"]["CountryID"] = 2
AtisStaticsPos["ATIS Shiraz Intl"]["y"] = -352967.25
AtisStaticsPos["ATIS Shiraz Intl"]["x"] = 382282.125
AtisStaticsPos["ATIS Shiraz Intl"]["CategoryID"] = 3
AtisStaticsPos["ATIS Shiraz Intl"]["heading"] = 3.6302848777646
AtisStaticsPos["ATIS Shiraz Intl"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Shiraz Intl"]["name"] = "ATIS Shiraz Intl"
AtisStaticsPos["ATIS Shiraz Intl"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Shiraz Intl"]["dead"] = false
AtisStaticsPos["ATIS Lar"] = {}
AtisStaticsPos["ATIS Lar"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Lar"]["CountryID"] = 2
AtisStaticsPos["ATIS Lar"]["y"] = -182522.59375
AtisStaticsPos["ATIS Lar"]["x"] = 168489.34375
AtisStaticsPos["ATIS Lar"]["CategoryID"] = 3
AtisStaticsPos["ATIS Lar"]["heading"] = 1.57079631487
AtisStaticsPos["ATIS Lar"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Lar"]["name"] = "ATIS Lar"
AtisStaticsPos["ATIS Lar"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Lar"]["dead"] = false
AtisStaticsPos["ATIS Abu Dhabi Intl"] = {}
AtisStaticsPos["ATIS Abu Dhabi Intl"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Abu Dhabi Intl"]["CountryID"] = 2
AtisStaticsPos["ATIS Abu Dhabi Intl"]["y"] = -163420.8125
AtisStaticsPos["ATIS Abu Dhabi Intl"]["x"] = -189042.71875
AtisStaticsPos["ATIS Abu Dhabi Intl"]["CategoryID"] = 3
AtisStaticsPos["ATIS Abu Dhabi Intl"]["heading"] = 5.7421331724118
AtisStaticsPos["ATIS Abu Dhabi Intl"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Abu Dhabi Intl"]["name"] = "ATIS Abu Dhabi Intl"
AtisStaticsPos["ATIS Abu Dhabi Intl"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Abu Dhabi Intl"]["dead"] = false
AtisStaticsPos["ATIS Sayqal"] = {} --Syria
AtisStaticsPos["ATIS Sayqal"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Sayqal"]["CountryID"] = 2
AtisStaticsPos["ATIS Sayqal"]["y"] = 117009.546875
AtisStaticsPos["ATIS Sayqal"]["x"] = -150942.484375
AtisStaticsPos["ATIS Sayqal"]["CategoryID"] = 3
AtisStaticsPos["ATIS Sayqal"]["heading"] = 4.1538835294539
AtisStaticsPos["ATIS Sayqal"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Sayqal"]["name"] = "ATIS Sayqal"
AtisStaticsPos["ATIS Sayqal"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Sayqal"]["dead"] = false
AtisStaticsPos["ATIS Marj as Sultan North"] = {}
AtisStaticsPos["ATIS Marj as Sultan North"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Marj as Sultan North"]["CountryID"] = 2
AtisStaticsPos["ATIS Marj as Sultan North"]["y"] = 47512.19140625
AtisStaticsPos["ATIS Marj as Sultan North"]["x"] = -169970.59375
AtisStaticsPos["ATIS Marj as Sultan North"]["CategoryID"] = 3
AtisStaticsPos["ATIS Marj as Sultan North"]["heading"] = 3.420522376796
AtisStaticsPos["ATIS Marj as Sultan North"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Marj as Sultan North"]["name"] = "ATIS Marj as Sultan North"
AtisStaticsPos["ATIS Marj as Sultan North"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Marj as Sultan North"]["dead"] = false
AtisStaticsPos["ATIS Naqoura"] = {}
AtisStaticsPos["ATIS Naqoura"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Naqoura"]["CountryID"] = 2
AtisStaticsPos["ATIS Naqoura"]["y"] = -78742.6640625
AtisStaticsPos["ATIS Naqoura"]["x"] = -210201.46875
AtisStaticsPos["ATIS Naqoura"]["CategoryID"] = 3
AtisStaticsPos["ATIS Naqoura"]["heading"] = 1.2915436603316
AtisStaticsPos["ATIS Naqoura"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Naqoura"]["name"] = "ATIS Naqoura"
AtisStaticsPos["ATIS Naqoura"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Naqoura"]["dead"] = false
AtisStaticsPos["ATIS Al Qusayr"] = {}
AtisStaticsPos["ATIS Al Qusayr"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Al Qusayr"]["CountryID"] = 2
AtisStaticsPos["ATIS Al Qusayr"]["y"] = 61372.89453125
AtisStaticsPos["ATIS Al Qusayr"]["x"] = -52636.5859375
AtisStaticsPos["ATIS Al Qusayr"]["CategoryID"] = 3
AtisStaticsPos["ATIS Al Qusayr"]["heading"] = 1.5358899292969
AtisStaticsPos["ATIS Al Qusayr"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Al Qusayr"]["name"] = "ATIS Al Qusayr"
AtisStaticsPos["ATIS Al Qusayr"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Al Qusayr"]["dead"] = false
AtisStaticsPos["ATIS Bassel Al-Assad"] = {}
AtisStaticsPos["ATIS Bassel Al-Assad"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Bassel Al-Assad"]["CountryID"] = 2
AtisStaticsPos["ATIS Bassel Al-Assad"]["y"] = 5115.2270507813
AtisStaticsPos["ATIS Bassel Al-Assad"]["x"] = 42915.26171875
AtisStaticsPos["ATIS Bassel Al-Assad"]["CategoryID"] = 3
AtisStaticsPos["ATIS Bassel Al-Assad"]["heading"] = 1.5359576026971
AtisStaticsPos["ATIS Bassel Al-Assad"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Bassel Al-Assad"]["name"] = "ATIS Bassel Al-Assad"
AtisStaticsPos["ATIS Bassel Al-Assad"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Bassel Al-Assad"]["dead"] = false
AtisStaticsPos["ATIS Abu al-Duhur"] = {}
AtisStaticsPos["ATIS Abu al-Duhur"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Abu al-Duhur"]["CountryID"] = 2
AtisStaticsPos["ATIS Abu al-Duhur"]["y"] = 112907.2734375
AtisStaticsPos["ATIS Abu al-Duhur"]["x"] = 76198.4453125
AtisStaticsPos["ATIS Abu al-Duhur"]["CategoryID"] = 3
AtisStaticsPos["ATIS Abu al-Duhur"]["heading"] = 0.052359886742702
AtisStaticsPos["ATIS Abu al-Duhur"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Abu al-Duhur"]["name"] = "ATIS Abu al-Duhur"
AtisStaticsPos["ATIS Abu al-Duhur"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Abu al-Duhur"]["dead"] = false
AtisStaticsPos["ATIS Ramat David"] = {}
AtisStaticsPos["ATIS Ramat David"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Ramat David"]["CountryID"] = 2
AtisStaticsPos["ATIS Ramat David"]["y"] = -74850.5234375
AtisStaticsPos["ATIS Ramat David"]["x"] = -258819.21875
AtisStaticsPos["ATIS Ramat David"]["CategoryID"] = 3
AtisStaticsPos["ATIS Ramat David"]["heading"] = 0.3488051406753
AtisStaticsPos["ATIS Ramat David"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Ramat David"]["name"] = "ATIS Ramat David"
AtisStaticsPos["ATIS Ramat David"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Ramat David"]["dead"] = false
AtisStaticsPos["ATIS H4"] = {}
AtisStaticsPos["ATIS H4"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS H4"]["CountryID"] = 2
AtisStaticsPos["ATIS H4"]["y"] = 206243
AtisStaticsPos["ATIS H4"]["x"] = -279293.125
AtisStaticsPos["ATIS H4"]["CategoryID"] = 3
AtisStaticsPos["ATIS H4"]["heading"] = 3.3684855158337
AtisStaticsPos["ATIS H4"]["type"] = "UH-1H"
AtisStaticsPos["ATIS H4"]["name"] = "ATIS H4"
AtisStaticsPos["ATIS H4"]["CoalitionID"] = 2
AtisStaticsPos["ATIS H4"]["dead"] = false
AtisStaticsPos["ATIS Megiddo"] = {}
AtisStaticsPos["ATIS Megiddo"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Megiddo"]["CountryID"] = 2
AtisStaticsPos["ATIS Megiddo"]["y"] = -70515.890625
AtisStaticsPos["ATIS Megiddo"]["x"] = -267337.625
AtisStaticsPos["ATIS Megiddo"]["CategoryID"] = 3
AtisStaticsPos["ATIS Megiddo"]["heading"] = 1.0297444885971
AtisStaticsPos["ATIS Megiddo"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Megiddo"]["name"] = "ATIS Megiddo"
AtisStaticsPos["ATIS Megiddo"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Megiddo"]["dead"] = false
AtisStaticsPos["ATIS Rayak"] = {}
AtisStaticsPos["ATIS Rayak"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Rayak"]["CountryID"] = 2
AtisStaticsPos["ATIS Rayak"]["y"] = 4621.9892578125
AtisStaticsPos["ATIS Rayak"]["x"] = -130044.890625
AtisStaticsPos["ATIS Rayak"]["CategoryID"] = 3
AtisStaticsPos["ATIS Rayak"]["heading"] = 5.5149402209806
AtisStaticsPos["ATIS Rayak"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Rayak"]["name"] = "ATIS Rayak"
AtisStaticsPos["ATIS Rayak"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Rayak"]["dead"] = false
AtisStaticsPos["ATIS Tabqa"] = {}
AtisStaticsPos["ATIS Tabqa"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Tabqa"]["CountryID"] = 2
AtisStaticsPos["ATIS Tabqa"]["y"] = 244618.578125
AtisStaticsPos["ATIS Tabqa"]["x"] = 77263.4921875
AtisStaticsPos["ATIS Tabqa"]["CategoryID"] = 3
AtisStaticsPos["ATIS Tabqa"]["heading"] = 3.1939526259283
AtisStaticsPos["ATIS Tabqa"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Tabqa"]["name"] = "ATIS Tabqa"
AtisStaticsPos["ATIS Tabqa"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Tabqa"]["dead"] = false
AtisStaticsPos["ATIS Aleppo"] = {}
AtisStaticsPos["ATIS Aleppo"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Aleppo"]["CountryID"] = 2
AtisStaticsPos["ATIS Aleppo"]["y"] = 123138.6328125
AtisStaticsPos["ATIS Aleppo"]["x"] = 125979.890625
AtisStaticsPos["ATIS Aleppo"]["CategoryID"] = 3
AtisStaticsPos["ATIS Aleppo"]["heading"] = 3.3335788919752
AtisStaticsPos["ATIS Aleppo"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Aleppo"]["name"] = "ATIS Aleppo"
AtisStaticsPos["ATIS Aleppo"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Aleppo"]["dead"] = false
AtisStaticsPos["ATIS Palmyra"] = {}
AtisStaticsPos["ATIS Palmyra"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Palmyra"]["CountryID"] = 2
AtisStaticsPos["ATIS Palmyra"]["y"] = 219837.640625
AtisStaticsPos["ATIS Palmyra"]["x"] = -55977.69921875
AtisStaticsPos["ATIS Palmyra"]["CategoryID"] = 3
AtisStaticsPos["ATIS Palmyra"]["heading"] = 6.1437447852141
AtisStaticsPos["ATIS Palmyra"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Palmyra"]["name"] = "ATIS Palmyra"
AtisStaticsPos["ATIS Palmyra"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Palmyra"]["dead"] = false
AtisStaticsPos["ATIS Tha'lah"] = {}
AtisStaticsPos["ATIS Tha'lah"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Tha'lah"]["CountryID"] = 2
AtisStaticsPos["ATIS Tha'lah"]["y"] = 39729.73046875
AtisStaticsPos["ATIS Tha'lah"]["x"] = -259335.75
AtisStaticsPos["ATIS Tha'lah"]["CategoryID"] = 3
AtisStaticsPos["ATIS Tha'lah"]["heading"] = 5.7594909543504
AtisStaticsPos["ATIS Tha'lah"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Tha'lah"]["name"] = "ATIS Tha'lah"
AtisStaticsPos["ATIS Tha'lah"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Tha'lah"]["dead"] = false
AtisStaticsPos["ATIS Damascus"] = {}
AtisStaticsPos["ATIS Damascus"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Damascus"]["CountryID"] = 2
AtisStaticsPos["ATIS Damascus"]["y"] = 51510.41015625
AtisStaticsPos["ATIS Damascus"]["x"] = -181031.828125
AtisStaticsPos["ATIS Damascus"]["CategoryID"] = 3
AtisStaticsPos["ATIS Damascus"]["heading"] = 0.89011795457893
AtisStaticsPos["ATIS Damascus"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Damascus"]["name"] = "ATIS Damascus"
AtisStaticsPos["ATIS Damascus"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Damascus"]["dead"] = false
AtisStaticsPos["ATIS Wujah Al Hajar"] = {}
AtisStaticsPos["ATIS Wujah Al Hajar"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Wujah Al Hajar"]["CountryID"] = 2
AtisStaticsPos["ATIS Wujah Al Hajar"]["y"] = -22907.908203125
AtisStaticsPos["ATIS Wujah Al Hajar"]["x"] = -81336.2265625
AtisStaticsPos["ATIS Wujah Al Hajar"]["CategoryID"] = 3
AtisStaticsPos["ATIS Wujah Al Hajar"]["heading"] = 0.66322502825206
AtisStaticsPos["ATIS Wujah Al Hajar"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Wujah Al Hajar"]["name"] = "ATIS Wujah Al Hajar"
AtisStaticsPos["ATIS Wujah Al Hajar"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Wujah Al Hajar"]["dead"] = false
AtisStaticsPos["ATIS Tiyas"] = {}
AtisStaticsPos["ATIS Tiyas"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Tiyas"]["CountryID"] = 2
AtisStaticsPos["ATIS Tiyas"]["y"] = 156426.734375
AtisStaticsPos["ATIS Tiyas"]["x"] = -58399.24609375
AtisStaticsPos["ATIS Tiyas"]["CategoryID"] = 3
AtisStaticsPos["ATIS Tiyas"]["heading"] = 4.7123889366733
AtisStaticsPos["ATIS Tiyas"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Tiyas"]["name"] = "ATIS Tiyas"
AtisStaticsPos["ATIS Tiyas"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Tiyas"]["dead"] = false
AtisStaticsPos["ATIS Incirlik"] = {}
AtisStaticsPos["ATIS Incirlik"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Incirlik"]["CountryID"] = 2
AtisStaticsPos["ATIS Incirlik"]["y"] = -35242.68359375
AtisStaticsPos["ATIS Incirlik"]["x"] = 220498.8125
AtisStaticsPos["ATIS Incirlik"]["CategoryID"] = 3
AtisStaticsPos["ATIS Incirlik"]["heading"] = 5.6546382967056
AtisStaticsPos["ATIS Incirlik"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Incirlik"]["name"] = "ATIS Incirlik"
AtisStaticsPos["ATIS Incirlik"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Incirlik"]["dead"] = false
AtisStaticsPos["ATIS Qabr as Sitt"] = {}
AtisStaticsPos["ATIS Qabr as Sitt"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Qabr as Sitt"]["CountryID"] = 2
AtisStaticsPos["ATIS Qabr as Sitt"]["y"] = 36845.42578125
AtisStaticsPos["ATIS Qabr as Sitt"]["x"] = -174585.828125
AtisStaticsPos["ATIS Qabr as Sitt"]["CategoryID"] = 3
AtisStaticsPos["ATIS Qabr as Sitt"]["heading"] = 2.8623457557545
AtisStaticsPos["ATIS Qabr as Sitt"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Qabr as Sitt"]["name"] = "ATIS Qabr as Sitt"
AtisStaticsPos["ATIS Qabr as Sitt"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Qabr as Sitt"]["dead"] = false
AtisStaticsPos["ATIS Gaziantep"] = {}
AtisStaticsPos["ATIS Gaziantep"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Gaziantep"]["CountryID"] = 2
AtisStaticsPos["ATIS Gaziantep"]["y"] = 146694.171875
AtisStaticsPos["ATIS Gaziantep"]["x"] = 210223.21875
AtisStaticsPos["ATIS Gaziantep"]["CategoryID"] = 3
AtisStaticsPos["ATIS Gaziantep"]["heading"] = 4.9218004656837
AtisStaticsPos["ATIS Gaziantep"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Gaziantep"]["name"] = "ATIS Gaziantep"
AtisStaticsPos["ATIS Gaziantep"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Gaziantep"]["dead"] = false
AtisStaticsPos["ATIS Rosh Pina"] = {}
AtisStaticsPos["ATIS Rosh Pina"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Rosh Pina"]["CountryID"] = 2
AtisStaticsPos["ATIS Rosh Pina"]["y"] = -37635.5859375
AtisStaticsPos["ATIS Rosh Pina"]["x"] = -225833.703125
AtisStaticsPos["ATIS Rosh Pina"]["CategoryID"] = 3
AtisStaticsPos["ATIS Rosh Pina"]["heading"] = 0.87280257597419
AtisStaticsPos["ATIS Rosh Pina"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Rosh Pina"]["name"] = "ATIS Rosh Pina"
AtisStaticsPos["ATIS Rosh Pina"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Rosh Pina"]["dead"] = false
AtisStaticsPos["ATIS An Nasiriyah"] = {}
AtisStaticsPos["ATIS An Nasiriyah"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS An Nasiriyah"]["CountryID"] = 2
AtisStaticsPos["ATIS An Nasiriyah"]["y"] = 85961.5546875
AtisStaticsPos["ATIS An Nasiriyah"]["x"] = -123461.1796875
AtisStaticsPos["ATIS An Nasiriyah"]["CategoryID"] = 3
AtisStaticsPos["ATIS An Nasiriyah"]["heading"] = 0.92520967848089
AtisStaticsPos["ATIS An Nasiriyah"]["type"] = "UH-1H"
AtisStaticsPos["ATIS An Nasiriyah"]["name"] = "ATIS An Nasiriyah"
AtisStaticsPos["ATIS An Nasiriyah"]["CoalitionID"] = 2
AtisStaticsPos["ATIS An Nasiriyah"]["dead"] = false
AtisStaticsPos["ATIS Beirut-Rafic Hariri"] = {}
AtisStaticsPos["ATIS Beirut-Rafic Hariri"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Beirut-Rafic Hariri"]["CountryID"] = 2
AtisStaticsPos["ATIS Beirut-Rafic Hariri"]["y"] = -41900.05859375
AtisStaticsPos["ATIS Beirut-Rafic Hariri"]["x"] = -131084.421875
AtisStaticsPos["ATIS Beirut-Rafic Hariri"]["CategoryID"] = 3
AtisStaticsPos["ATIS Beirut-Rafic Hariri"]["heading"] = 4.6425756836651
AtisStaticsPos["ATIS Beirut-Rafic Hariri"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Beirut-Rafic Hariri"]["name"] = "ATIS Beirut-Rafic Hariri"
AtisStaticsPos["ATIS Beirut-Rafic Hariri"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Beirut-Rafic Hariri"]["dead"] = false
AtisStaticsPos["ATIS Marj as Sultan South"] = {}
AtisStaticsPos["ATIS Marj as Sultan South"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Marj as Sultan South"]["CountryID"] = 2
AtisStaticsPos["ATIS Marj as Sultan South"]["y"] = 48059.9296875
AtisStaticsPos["ATIS Marj as Sultan South"]["x"] = -171793.140625
AtisStaticsPos["ATIS Marj as Sultan South"]["CategoryID"] = 3
AtisStaticsPos["ATIS Marj as Sultan South"]["heading"] = 1.5883580137075
AtisStaticsPos["ATIS Marj as Sultan South"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Marj as Sultan South"]["name"] = "ATIS Marj as Sultan South"
AtisStaticsPos["ATIS Marj as Sultan South"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Marj as Sultan South"]["dead"] = false
AtisStaticsPos["ATIS King Hussein Air College"] = {}
AtisStaticsPos["ATIS King Hussein Air College"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS King Hussein Air College"]["CountryID"] = 2
AtisStaticsPos["ATIS King Hussein Air College"]["y"] = 24275.162109375
AtisStaticsPos["ATIS King Hussein Air College"]["x"] = -295242.4375
AtisStaticsPos["ATIS King Hussein Air College"]["CategoryID"] = 3
AtisStaticsPos["ATIS King Hussein Air College"]["heading"] = 3.7873645371225
AtisStaticsPos["ATIS King Hussein Air College"]["type"] = "UH-1H"
AtisStaticsPos["ATIS King Hussein Air College"]["name"] = "ATIS King Hussein Air College"
AtisStaticsPos["ATIS King Hussein Air College"]["CoalitionID"] = 2
AtisStaticsPos["ATIS King Hussein Air College"]["dead"] = false
AtisStaticsPos["ATIS Kuweires"] = {}
AtisStaticsPos["ATIS Kuweires"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Kuweires"]["CountryID"] = 2
AtisStaticsPos["ATIS Kuweires"]["y"] = 154797.109375
AtisStaticsPos["ATIS Kuweires"]["x"] = 125325.4296875
AtisStaticsPos["ATIS Kuweires"]["CategoryID"] = 3
AtisStaticsPos["ATIS Kuweires"]["heading"] = 0.19198638471316
AtisStaticsPos["ATIS Kuweires"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Kuweires"]["name"] = "ATIS Kuweires"
AtisStaticsPos["ATIS Kuweires"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Kuweires"]["dead"] = false
AtisStaticsPos["ATIS Hama"] = {}
AtisStaticsPos["ATIS Hama"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Hama"]["CountryID"] = 2
AtisStaticsPos["ATIS Hama"]["y"] = 73964.890625
AtisStaticsPos["ATIS Hama"]["x"] = 9171.4091796875
AtisStaticsPos["ATIS Hama"]["CategoryID"] = 3
AtisStaticsPos["ATIS Hama"]["heading"] = 2.7227137565031
AtisStaticsPos["ATIS Hama"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Hama"]["name"] = "ATIS Hama"
AtisStaticsPos["ATIS Hama"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Hama"]["dead"] = false
AtisStaticsPos["ATIS Al-Dumayr"] = {}
AtisStaticsPos["ATIS Al-Dumayr"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Al-Dumayr"]["CountryID"] = 2
AtisStaticsPos["ATIS Al-Dumayr"]["y"] = 73980.421875
AtisStaticsPos["ATIS Al-Dumayr"]["x"] = -158128.75
AtisStaticsPos["ATIS Al-Dumayr"]["CategoryID"] = 3
AtisStaticsPos["ATIS Al-Dumayr"]["heading"] = 2.6703537138866
AtisStaticsPos["ATIS Al-Dumayr"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Al-Dumayr"]["name"] = "ATIS Al-Dumayr"
AtisStaticsPos["ATIS Al-Dumayr"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Al-Dumayr"]["dead"] = false
AtisStaticsPos["ATIS Mezzeh"] = {}
AtisStaticsPos["ATIS Mezzeh"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Mezzeh"]["CountryID"] = 2
AtisStaticsPos["ATIS Mezzeh"]["y"] = 24431.068359375
AtisStaticsPos["ATIS Mezzeh"]["x"] = -172015.84375
AtisStaticsPos["ATIS Mezzeh"]["CategoryID"] = 3
AtisStaticsPos["ATIS Mezzeh"]["heading"] = 2.6003416815269
AtisStaticsPos["ATIS Mezzeh"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Mezzeh"]["name"] = "ATIS Mezzeh"
AtisStaticsPos["ATIS Mezzeh"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Mezzeh"]["dead"] = false
AtisStaticsPos["ATIS Adana Sakirpasa"] = {}
AtisStaticsPos["ATIS Adana Sakirpasa"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Adana Sakirpasa"]["CountryID"] = 2
AtisStaticsPos["ATIS Adana Sakirpasa"]["y"] = -47472.37109375
AtisStaticsPos["ATIS Adana Sakirpasa"]["x"] = 219514.53125
AtisStaticsPos["ATIS Adana Sakirpasa"]["CategoryID"] = 3
AtisStaticsPos["ATIS Adana Sakirpasa"]["heading"] = 0.1745327103881
AtisStaticsPos["ATIS Adana Sakirpasa"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Adana Sakirpasa"]["name"] = "ATIS Adana Sakirpasa"
AtisStaticsPos["ATIS Adana Sakirpasa"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Adana Sakirpasa"]["dead"] = false
AtisStaticsPos["ATIS Khalkhalah"] = {}
AtisStaticsPos["ATIS Khalkhalah"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Khalkhalah"]["CountryID"] = 2
AtisStaticsPos["ATIS Khalkhalah"]["y"] = 53908.9609375
AtisStaticsPos["ATIS Khalkhalah"]["x"] = -217893.0625
AtisStaticsPos["ATIS Khalkhalah"]["CategoryID"] = 3
AtisStaticsPos["ATIS Khalkhalah"]["heading"] = 2.6005444229584
AtisStaticsPos["ATIS Khalkhalah"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Khalkhalah"]["name"] = "ATIS Khalkhalah"
AtisStaticsPos["ATIS Khalkhalah"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Khalkhalah"]["dead"] = false
AtisStaticsPos["ATIS Kiryat Shmona"] = {}
AtisStaticsPos["ATIS Kiryat Shmona"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Kiryat Shmona"]["CountryID"] = 2
AtisStaticsPos["ATIS Kiryat Shmona"]["y"] = -35372.93359375
AtisStaticsPos["ATIS Kiryat Shmona"]["x"] = -199940.15625
AtisStaticsPos["ATIS Kiryat Shmona"]["CategoryID"] = 3
AtisStaticsPos["ATIS Kiryat Shmona"]["heading"] = 2.670422171932
AtisStaticsPos["ATIS Kiryat Shmona"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Kiryat Shmona"]["name"] = "ATIS Kiryat Shmona"
AtisStaticsPos["ATIS Kiryat Shmona"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Kiryat Shmona"]["dead"] = false
AtisStaticsPos["ATIS Haifa"] = {}
AtisStaticsPos["ATIS Haifa"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Haifa"]["CountryID"] = 2
AtisStaticsPos["ATIS Haifa"]["y"] = -87774.9453125
AtisStaticsPos["ATIS Haifa"]["x"] = -242884.625
AtisStaticsPos["ATIS Haifa"]["CategoryID"] = 3
AtisStaticsPos["ATIS Haifa"]["heading"] = 1.291543802647
AtisStaticsPos["ATIS Haifa"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Haifa"]["name"] = "ATIS Haifa"
AtisStaticsPos["ATIS Haifa"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Haifa"]["dead"] = false
AtisStaticsPos["ATIS Eyn Shemer"] = {}
AtisStaticsPos["ATIS Eyn Shemer"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Eyn Shemer"]["CountryID"] = 2
AtisStaticsPos["ATIS Eyn Shemer"]["y"] = -92593.5703125
AtisStaticsPos["ATIS Eyn Shemer"]["x"] = -283576.9375
AtisStaticsPos["ATIS Eyn Shemer"]["CategoryID"] = 3
AtisStaticsPos["ATIS Eyn Shemer"]["heading"] = 0.19187193830264
AtisStaticsPos["ATIS Eyn Shemer"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Eyn Shemer"]["name"] = "ATIS Eyn Shemer"
AtisStaticsPos["ATIS Eyn Shemer"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Eyn Shemer"]["dead"] = false
AtisStaticsPos["ATIS Hatay"] = {}
AtisStaticsPos["ATIS Hatay"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Hatay"]["CountryID"] = 2
AtisStaticsPos["ATIS Hatay"]["y"] = 38783.62890625
AtisStaticsPos["ATIS Hatay"]["x"] = 147667.140625
AtisStaticsPos["ATIS Hatay"]["CategoryID"] = 3
AtisStaticsPos["ATIS Hatay"]["heading"] = 2.3911158337648
AtisStaticsPos["ATIS Hatay"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Hatay"]["name"] = "ATIS Hatay"
AtisStaticsPos["ATIS Hatay"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Hatay"]["dead"] = false
AtisStaticsPos["ATIS Minakh"] = {}
AtisStaticsPos["ATIS Minakh"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Minakh"]["CountryID"] = 2
AtisStaticsPos["ATIS Minakh"]["y"] = 107226.9375
AtisStaticsPos["ATIS Minakh"]["x"] = 163516.53125
AtisStaticsPos["ATIS Minakh"]["CategoryID"] = 3
AtisStaticsPos["ATIS Minakh"]["heading"] = 0
AtisStaticsPos["ATIS Minakh"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Minakh"]["name"] = "ATIS Minakh"
AtisStaticsPos["ATIS Minakh"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Minakh"]["dead"] = false
AtisStaticsPos["ATIS Jirah"] = {}
AtisStaticsPos["ATIS Jirah"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Jirah"]["CountryID"] = 2
AtisStaticsPos["ATIS Jirah"]["y"] = 188539.140625
AtisStaticsPos["ATIS Jirah"]["x"] = 115190.3984375
AtisStaticsPos["ATIS Jirah"]["CategoryID"] = 3
AtisStaticsPos["ATIS Jirah"]["heading"] = 0.19189057387965
AtisStaticsPos["ATIS Jirah"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Jirah"]["name"] = "ATIS Jirah"
AtisStaticsPos["ATIS Jirah"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Jirah"]["dead"] = false
AtisStaticsPos["ATIS Marj Ruhayyil"] = {}
AtisStaticsPos["ATIS Marj Ruhayyil"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Marj Ruhayyil"]["CountryID"] = 2
AtisStaticsPos["ATIS Marj Ruhayyil"]["y"] = 45971.4921875
AtisStaticsPos["ATIS Marj Ruhayyil"]["x"] = -193030.84375
AtisStaticsPos["ATIS Marj Ruhayyil"]["CategoryID"] = 3
AtisStaticsPos["ATIS Marj Ruhayyil"]["heading"] = 1.7622398794294
AtisStaticsPos["ATIS Marj Ruhayyil"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Marj Ruhayyil"]["name"] = "ATIS Marj Ruhayyil"
AtisStaticsPos["ATIS Marj Ruhayyil"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Marj Ruhayyil"]["dead"] = false
AtisStaticsPos["ATIS Taftanaz"] = {}
AtisStaticsPos["ATIS Taftanaz"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Taftanaz"]["CountryID"] = 2
AtisStaticsPos["ATIS Taftanaz"]["y"] = 82940.7421875
AtisStaticsPos["ATIS Taftanaz"]["x"] = 103798.0859375
AtisStaticsPos["ATIS Taftanaz"]["CategoryID"] = 3
AtisStaticsPos["ATIS Taftanaz"]["heading"] = 3.420845337465
AtisStaticsPos["ATIS Taftanaz"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Taftanaz"]["name"] = "ATIS Taftanaz"
AtisStaticsPos["ATIS Taftanaz"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Taftanaz"]["dead"] = false
AtisStaticsPos["ATIS Shayrat"] = {}
AtisStaticsPos["ATIS Shayrat"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Shayrat"]["CountryID"] = 2
AtisStaticsPos["ATIS Shayrat"]["y"] = 91674.6875
AtisStaticsPos["ATIS Shayrat"]["x"] = -60824.50390625
AtisStaticsPos["ATIS Shayrat"]["CategoryID"] = 3
AtisStaticsPos["ATIS Shayrat"]["heading"] = 3.8048177655381
AtisStaticsPos["ATIS Shayrat"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Shayrat"]["name"] = "ATIS Shayrat"
AtisStaticsPos["ATIS Shayrat"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Shayrat"]["dead"] = false
AtisStaticsPos["ATIS Rene Mouawad"] = {}
AtisStaticsPos["ATIS Rene Mouawad"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Rene Mouawad"]["CountryID"] = 2
AtisStaticsPos["ATIS Rene Mouawad"]["y"] = 8537.21875
AtisStaticsPos["ATIS Rene Mouawad"]["x"] = -47984.59375
AtisStaticsPos["ATIS Rene Mouawad"]["CategoryID"] = 3
AtisStaticsPos["ATIS Rene Mouawad"]["heading"] = 2.6354473322669
AtisStaticsPos["ATIS Rene Mouawad"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Rene Mouawad"]["name"] = "ATIS Rene Mouawad"
AtisStaticsPos["ATIS Rene Mouawad"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Rene Mouawad"]["dead"] = false
AtisStaticsPos["ATIS Creech AFB"] = {}  ---Nevada
AtisStaticsPos["ATIS Creech AFB"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Creech AFB"]["CountryID"] = 2
AtisStaticsPos["ATIS Creech AFB"]["y"] = -75144.6640625
AtisStaticsPos["ATIS Creech AFB"]["x"] = -360826.75
AtisStaticsPos["ATIS Creech AFB"]["CategoryID"] = 3
AtisStaticsPos["ATIS Creech AFB"]["heading"] = 0.034906688000728
AtisStaticsPos["ATIS Creech AFB"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Creech AFB"]["name"] = "ATIS Creech AFB"
AtisStaticsPos["ATIS Creech AFB"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Creech AFB"]["dead"] = false
AtisStaticsPos["ATIS Beatty Airport"] = {}
AtisStaticsPos["ATIS Beatty Airport"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Beatty Airport"]["CountryID"] = 2
AtisStaticsPos["ATIS Beatty Airport"]["y"] = -174819.171875
AtisStaticsPos["ATIS Beatty Airport"]["x"] = -329773.125
AtisStaticsPos["ATIS Beatty Airport"]["CategoryID"] = 3
AtisStaticsPos["ATIS Beatty Airport"]["heading"] = 6.283068830042
AtisStaticsPos["ATIS Beatty Airport"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Beatty Airport"]["name"] = "ATIS Beatty Airport"
AtisStaticsPos["ATIS Beatty Airport"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Beatty Airport"]["dead"] = false
AtisStaticsPos["ATIS North Las Vegas"] = {}
AtisStaticsPos["ATIS North Las Vegas"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS North Las Vegas"]["CountryID"] = 2
AtisStaticsPos["ATIS North Las Vegas"]["y"] = -31006.939453125
AtisStaticsPos["ATIS North Las Vegas"]["x"] = -401114.6875
AtisStaticsPos["ATIS North Las Vegas"]["CategoryID"] = 3
AtisStaticsPos["ATIS North Las Vegas"]["heading"] = 4.6600288777917
AtisStaticsPos["ATIS North Las Vegas"]["type"] = "UH-1H"
AtisStaticsPos["ATIS North Las Vegas"]["name"] = "ATIS North Las Vegas"
AtisStaticsPos["ATIS North Las Vegas"]["CoalitionID"] = 2
AtisStaticsPos["ATIS North Las Vegas"]["dead"] = false
AtisStaticsPos["ATIS Tonopah Test Range Airfield"] = {}
AtisStaticsPos["ATIS Tonopah Test Range Airfield"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Tonopah Test Range Airfield"]["CountryID"] = 2
AtisStaticsPos["ATIS Tonopah Test Range Airfield"]["y"] = -174118.171875
AtisStaticsPos["ATIS Tonopah Test Range Airfield"]["x"] = -226227.140625
AtisStaticsPos["ATIS Tonopah Test Range Airfield"]["CategoryID"] = 3
AtisStaticsPos["ATIS Tonopah Test Range Airfield"]["heading"] = 4.345870102994
AtisStaticsPos["ATIS Tonopah Test Range Airfield"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Tonopah Test Range Airfield"]["name"] = "ATIS Tonopah Test Range Airfield"
AtisStaticsPos["ATIS Tonopah Test Range Airfield"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Tonopah Test Range Airfield"]["dead"] = false
AtisStaticsPos["ATIS Boulder City Airport"] = {}
AtisStaticsPos["ATIS Boulder City Airport"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Boulder City Airport"]["CountryID"] = 2
AtisStaticsPos["ATIS Boulder City Airport"]["y"] = -690.23468017578
AtisStaticsPos["ATIS Boulder City Airport"]["x"] = -429615.375
AtisStaticsPos["ATIS Boulder City Airport"]["CategoryID"] = 3
AtisStaticsPos["ATIS Boulder City Airport"]["heading"] = 3.2637217638999
AtisStaticsPos["ATIS Boulder City Airport"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Boulder City Airport"]["name"] = "ATIS Boulder City Airport"
AtisStaticsPos["ATIS Boulder City Airport"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Boulder City Airport"]["dead"] = false
AtisStaticsPos["ATIS Henderson Executive Airport"] = {}
AtisStaticsPos["ATIS Henderson Executive Airport"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Henderson Executive Airport"]["CountryID"] = 2
AtisStaticsPos["ATIS Henderson Executive Airport"]["y"] = -26202.18359375
AtisStaticsPos["ATIS Henderson Executive Airport"]["x"] = -427089.90625
AtisStaticsPos["ATIS Henderson Executive Airport"]["CategoryID"] = 3
AtisStaticsPos["ATIS Henderson Executive Airport"]["heading"] = 1.5707261589031
AtisStaticsPos["ATIS Henderson Executive Airport"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Henderson Executive Airport"]["name"] = "ATIS Henderson Executive Airport"
AtisStaticsPos["ATIS Henderson Executive Airport"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Henderson Executive Airport"]["dead"] = false
AtisStaticsPos["ATIS Lincoln County"] = {}
AtisStaticsPos["ATIS Lincoln County"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Lincoln County"]["CountryID"] = 2
AtisStaticsPos["ATIS Lincoln County"]["y"] = 33358.01171875
AtisStaticsPos["ATIS Lincoln County"]["x"] = -224245.25
AtisStaticsPos["ATIS Lincoln County"]["CategoryID"] = 3
AtisStaticsPos["ATIS Lincoln County"]["heading"] = 0
AtisStaticsPos["ATIS Lincoln County"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Lincoln County"]["name"] = "ATIS Lincoln County"
AtisStaticsPos["ATIS Lincoln County"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Lincoln County"]["dead"] = false
AtisStaticsPos["ATIS Pahute Mesa Airstrip"] = {}
AtisStaticsPos["ATIS Pahute Mesa Airstrip"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Pahute Mesa Airstrip"]["CountryID"] = 2
AtisStaticsPos["ATIS Pahute Mesa Airstrip"]["y"] = -132990.359375
AtisStaticsPos["ATIS Pahute Mesa Airstrip"]["x"] = -303460.09375
AtisStaticsPos["ATIS Pahute Mesa Airstrip"]["CategoryID"] = 3
AtisStaticsPos["ATIS Pahute Mesa Airstrip"]["heading"] = 3.3335788919752
AtisStaticsPos["ATIS Pahute Mesa Airstrip"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Pahute Mesa Airstrip"]["name"] = "ATIS Pahute Mesa Airstrip"
AtisStaticsPos["ATIS Pahute Mesa Airstrip"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Pahute Mesa Airstrip"]["dead"] = false
AtisStaticsPos["ATIS Mesquite"] = {}
AtisStaticsPos["ATIS Mesquite"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Mesquite"]["CountryID"] = 2
AtisStaticsPos["ATIS Mesquite"]["y"] = 68339.1328125
AtisStaticsPos["ATIS Mesquite"]["x"] = -329787.46875
AtisStaticsPos["ATIS Mesquite"]["CategoryID"] = 3
AtisStaticsPos["ATIS Mesquite"]["heading"] = 2.0420353998234
AtisStaticsPos["ATIS Mesquite"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Mesquite"]["name"] = "ATIS Mesquite"
AtisStaticsPos["ATIS Mesquite"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Mesquite"]["dead"] = false
AtisStaticsPos["ATIS Echo Bay"] = {}
AtisStaticsPos["ATIS Echo Bay"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Echo Bay"]["CountryID"] = 2
AtisStaticsPos["ATIS Echo Bay"]["y"] = 33624.1484375
AtisStaticsPos["ATIS Echo Bay"]["x"] = -388543.5
AtisStaticsPos["ATIS Echo Bay"]["CategoryID"] = 3
AtisStaticsPos["ATIS Echo Bay"]["heading"] = 3.420460623074
AtisStaticsPos["ATIS Echo Bay"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Echo Bay"]["name"] = "ATIS Echo Bay"
AtisStaticsPos["ATIS Echo Bay"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Echo Bay"]["dead"] = false
AtisStaticsPos["ATIS McCarran International Airport"] = {}
AtisStaticsPos["ATIS McCarran International Airport"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS McCarran International Airport"]["CountryID"] = 2
AtisStaticsPos["ATIS McCarran International Airport"]["y"] = -26912.173828125
AtisStaticsPos["ATIS McCarran International Airport"]["x"] = -415480.65625
AtisStaticsPos["ATIS McCarran International Airport"]["CategoryID"] = 3
AtisStaticsPos["ATIS McCarran International Airport"]["heading"] = 4.4344229184584
AtisStaticsPos["ATIS McCarran International Airport"]["type"] = "UH-1H"
AtisStaticsPos["ATIS McCarran International Airport"]["name"] = "ATIS McCarran International Airport"
AtisStaticsPos["ATIS McCarran International Airport"]["CoalitionID"] = 2
AtisStaticsPos["ATIS McCarran International Airport"]["dead"] = false
AtisStaticsPos["ATIS Nellis AFB"] = {}
AtisStaticsPos["ATIS Nellis AFB"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Nellis AFB"]["CountryID"] = 2
AtisStaticsPos["ATIS Nellis AFB"]["y"] = -17124.751953125
AtisStaticsPos["ATIS Nellis AFB"]["x"] = -396616.625
AtisStaticsPos["ATIS Nellis AFB"]["CategoryID"] = 3
AtisStaticsPos["ATIS Nellis AFB"]["heading"] = 6.283162673753
AtisStaticsPos["ATIS Nellis AFB"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Nellis AFB"]["name"] = "ATIS Nellis AFB"
AtisStaticsPos["ATIS Nellis AFB"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Nellis AFB"]["dead"] = false
AtisStaticsPos["ATIS Groom Lake AFB"] = {}
AtisStaticsPos["ATIS Groom Lake AFB"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Groom Lake AFB"]["CountryID"] = 2
AtisStaticsPos["ATIS Groom Lake AFB"]["y"] = -88856.265625
AtisStaticsPos["ATIS Groom Lake AFB"]["x"] = -288548.03125
AtisStaticsPos["ATIS Groom Lake AFB"]["CategoryID"] = 3
AtisStaticsPos["ATIS Groom Lake AFB"]["heading"] = 1.500930113699
AtisStaticsPos["ATIS Groom Lake AFB"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Groom Lake AFB"]["name"] = "ATIS Groom Lake AFB"
AtisStaticsPos["ATIS Groom Lake AFB"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Groom Lake AFB"]["dead"] = false
AtisStaticsPos["ATIS Tonopah Airport"] = {}
AtisStaticsPos["ATIS Tonopah Airport"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Tonopah Airport"]["CountryID"] = 2
AtisStaticsPos["ATIS Tonopah Airport"]["y"] = -202422.75
AtisStaticsPos["ATIS Tonopah Airport"]["x"] = -197205.515625
AtisStaticsPos["ATIS Tonopah Airport"]["CategoryID"] = 3
AtisStaticsPos["ATIS Tonopah Airport"]["heading"] = 2.0420353998234
AtisStaticsPos["ATIS Tonopah Airport"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Tonopah Airport"]["name"] = "ATIS Tonopah Airport"
AtisStaticsPos["ATIS Tonopah Airport"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Tonopah Airport"]["dead"] = false
AtisStaticsPos["ATIS Laughlin Airport"] = {}
AtisStaticsPos["ATIS Laughlin Airport"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Laughlin Airport"]["CountryID"] = 2
AtisStaticsPos["ATIS Laughlin Airport"]["y"] = 28445.501953125
AtisStaticsPos["ATIS Laughlin Airport"]["x"] = -516316.25
AtisStaticsPos["ATIS Laughlin Airport"]["CategoryID"] = 3
AtisStaticsPos["ATIS Laughlin Airport"]["heading"] = 6.2133722376745
AtisStaticsPos["ATIS Laughlin Airport"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Laughlin Airport"]["name"] = "ATIS Laughlin Airport"
AtisStaticsPos["ATIS Laughlin Airport"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Laughlin Airport"]["dead"] = false
AtisStaticsPos["ATIS Mina Airport 3Q0"] = {}
AtisStaticsPos["ATIS Mina Airport 3Q0"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Mina Airport 3Q0"]["CountryID"] = 2
AtisStaticsPos["ATIS Mina Airport 3Q0"]["y"] = -290250.65625
AtisStaticsPos["ATIS Mina Airport 3Q0"]["x"] = -160899.25
AtisStaticsPos["ATIS Mina Airport 3Q0"]["CategoryID"] = 3
AtisStaticsPos["ATIS Mina Airport 3Q0"]["heading"] = 2.0414938150212
AtisStaticsPos["ATIS Mina Airport 3Q0"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Mina Airport 3Q0"]["name"] = "ATIS Mina Airport 3Q0"
AtisStaticsPos["ATIS Mina Airport 3Q0"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Mina Airport 3Q0"]["dead"] = false
AtisStaticsPos["ATIS Jean Airport"] = {}
AtisStaticsPos["ATIS Jean Airport"]["shape_name"] = "UH-1H"
AtisStaticsPos["ATIS Jean Airport"]["CountryID"] = 2
AtisStaticsPos["ATIS Jean Airport"]["y"] = -43028.15625
AtisStaticsPos["ATIS Jean Airport"]["x"] = -450145.09375
AtisStaticsPos["ATIS Jean Airport"]["CategoryID"] = 3
AtisStaticsPos["ATIS Jean Airport"]["heading"] = 2.1118481649927
AtisStaticsPos["ATIS Jean Airport"]["type"] = "UH-1H"
AtisStaticsPos["ATIS Jean Airport"]["name"] = "ATIS Jean Airport"
AtisStaticsPos["ATIS Jean Airport"]["CoalitionID"] = 2
AtisStaticsPos["ATIS Jean Airport"]["dead"] = false
