Ugly.AtisStatics = {}
Ugly.AtisStatics["ATIS Mozdok"] = {} ---Caucasus
Ugly.AtisStatics["ATIS Mozdok"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Mozdok"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Mozdok"]["y"] = 835129.25
Ugly.AtisStatics["ATIS Mozdok"]["x"] = -83958.40625
Ugly.AtisStatics["ATIS Mozdok"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Mozdok"]["heading"] = 4.555309243523
Ugly.AtisStatics["ATIS Mozdok"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Mozdok"]["name"] = "ATIS Mozdok"
Ugly.AtisStatics["ATIS Mozdok"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Mozdok"]["dead"] = false
Ugly.AtisStatics["ATIS Krasnodar-Center"] = {}
Ugly.AtisStatics["ATIS Krasnodar-Center"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Krasnodar-Center"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Krasnodar-Center"]["y"] = 367821.9375
Ugly.AtisStatics["ATIS Krasnodar-Center"]["x"] = 11027.486328125
Ugly.AtisStatics["ATIS Krasnodar-Center"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Krasnodar-Center"]["heading"] = 6.2657318130675
Ugly.AtisStatics["ATIS Krasnodar-Center"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Krasnodar-Center"]["name"] = "ATIS Krasnodar-Center"
Ugly.AtisStatics["ATIS Krasnodar-Center"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Krasnodar-Center"]["dead"] = false
Ugly.AtisStatics["ATIS Sukhumi-Babushara"] = {}
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["y"] = 563717.8125
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["x"] = -219676.0625
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["heading"] = 3.0543263631973
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["name"] = "ATIS Sukhumi-Babushara"
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sukhumi-Babushara"]["dead"] = false
Ugly.AtisStatics["ATIS Maykop-Khanskaya"] = {}
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["y"] = 457873.125
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["x"] = -27874.431640625
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["heading"] = 5.0440016426324
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["name"] = "ATIS Maykop-Khanskaya"
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Maykop-Khanskaya"]["dead"] = false
Ugly.AtisStatics["ATIS Gudauta"] = {}
Ugly.AtisStatics["ATIS Gudauta"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Gudauta"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Gudauta"]["y"] = 515909.65625
Ugly.AtisStatics["ATIS Gudauta"]["x"] = -196307.609375
Ugly.AtisStatics["ATIS Gudauta"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Gudauta"]["heading"] = 1.3788102314818
Ugly.AtisStatics["ATIS Gudauta"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Gudauta"]["name"] = "ATIS Gudauta"
Ugly.AtisStatics["ATIS Gudauta"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Gudauta"]["dead"] = false
Ugly.AtisStatics["ATIS Batumi"] = {}
Ugly.AtisStatics["ATIS Batumi"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Batumi"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Batumi"]["y"] = 618278.0625
Ugly.AtisStatics["ATIS Batumi"]["x"] = -355994.78125
Ugly.AtisStatics["ATIS Batumi"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Batumi"]["heading"] = 5.6897735744878
Ugly.AtisStatics["ATIS Batumi"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Batumi"]["name"] = "ATIS Batumi"
Ugly.AtisStatics["ATIS Batumi"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Batumi"]["dead"] = false
Ugly.AtisStatics["ATIS Nalchik"] = {}
Ugly.AtisStatics["ATIS Nalchik"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Nalchik"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Nalchik"]["y"] = 760368.1875
Ugly.AtisStatics["ATIS Nalchik"]["x"] = -125526.4765625
Ugly.AtisStatics["ATIS Nalchik"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Nalchik"]["heading"] = 5.6897735744878
Ugly.AtisStatics["ATIS Nalchik"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Nalchik"]["name"] = "ATIS Nalchik"
Ugly.AtisStatics["ATIS Nalchik"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Nalchik"]["dead"] = false
Ugly.AtisStatics["ATIS Soganlug"] = {}
Ugly.AtisStatics["ATIS Soganlug"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Soganlug"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Soganlug"]["y"] = 894205.1875
Ugly.AtisStatics["ATIS Soganlug"]["x"] = -317181.875
Ugly.AtisStatics["ATIS Soganlug"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Soganlug"]["heading"] = 1.675545322808
Ugly.AtisStatics["ATIS Soganlug"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Soganlug"]["name"] = "ATIS Soganlug"
Ugly.AtisStatics["ATIS Soganlug"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Soganlug"]["dead"] = false
Ugly.AtisStatics["ATIS Senaki-Kolkhi"] = {}
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["y"] = 646339.3125
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["x"] = -281390.71875
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["heading"] = 3.8920841443008
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["name"] = "ATIS Senaki-Kolkhi"
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Senaki-Kolkhi"]["dead"] = false
Ugly.AtisStatics["ATIS Gelendzhik"] = {}
Ugly.AtisStatics["ATIS Gelendzhik"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Gelendzhik"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Gelendzhik"]["y"] = 298190.84375
Ugly.AtisStatics["ATIS Gelendzhik"]["x"] = -50243.09375
Ugly.AtisStatics["ATIS Gelendzhik"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Gelendzhik"]["heading"] = 0.62831861911703
Ugly.AtisStatics["ATIS Gelendzhik"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Gelendzhik"]["name"] = "ATIS Gelendzhik"
Ugly.AtisStatics["ATIS Gelendzhik"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Gelendzhik"]["dead"] = false
Ugly.AtisStatics["ATIS Vaziani"] = {}
Ugly.AtisStatics["ATIS Vaziani"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Vaziani"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Vaziani"]["y"] = 904161.25
Ugly.AtisStatics["ATIS Vaziani"]["x"] = -319626.34375
Ugly.AtisStatics["ATIS Vaziani"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Vaziani"]["heading"] = 0.76794466032744
Ugly.AtisStatics["ATIS Vaziani"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Vaziani"]["name"] = "ATIS Vaziani"
Ugly.AtisStatics["ATIS Vaziani"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Vaziani"]["dead"] = false
Ugly.AtisStatics["ATIS Sochi-Adler"] = {}
Ugly.AtisStatics["ATIS Sochi-Adler"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sochi-Adler"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sochi-Adler"]["y"] = 461336.5
Ugly.AtisStatics["ATIS Sochi-Adler"]["x"] = -164620.296875
Ugly.AtisStatics["ATIS Sochi-Adler"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sochi-Adler"]["heading"] = 2.6529005100552
Ugly.AtisStatics["ATIS Sochi-Adler"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sochi-Adler"]["name"] = "ATIS Sochi-Adler"
Ugly.AtisStatics["ATIS Sochi-Adler"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sochi-Adler"]["dead"] = false
Ugly.AtisStatics["ATIS Kobuleti"] = {}
Ugly.AtisStatics["ATIS Kobuleti"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kobuleti"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kobuleti"]["y"] = 636647.125
Ugly.AtisStatics["ATIS Kobuleti"]["x"] = -317259.28125
Ugly.AtisStatics["ATIS Kobuleti"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kobuleti"]["heading"] = 4.3633232644329
Ugly.AtisStatics["ATIS Kobuleti"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kobuleti"]["name"] = "ATIS Kobuleti"
Ugly.AtisStatics["ATIS Kobuleti"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kobuleti"]["dead"] = false
Ugly.AtisStatics["ATIS Novorossiysk"] = {}
Ugly.AtisStatics["ATIS Novorossiysk"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Novorossiysk"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Novorossiysk"]["y"] = 279314.53125
Ugly.AtisStatics["ATIS Novorossiysk"]["x"] = -40217.9140625
Ugly.AtisStatics["ATIS Novorossiysk"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Novorossiysk"]["heading"] = 2.6878071650875
Ugly.AtisStatics["ATIS Novorossiysk"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Novorossiysk"]["name"] = "ATIS Novorossiysk"
Ugly.AtisStatics["ATIS Novorossiysk"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Novorossiysk"]["dead"] = false
Ugly.AtisStatics["ATIS Anapa-Vityazevo"] = {}
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["y"] = 242350.765625
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["x"] = -5558.6787109375
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["heading"] = 3.3161256972962
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["name"] = "ATIS Anapa-Vityazevo"
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Anapa-Vityazevo"]["dead"] = false
Ugly.AtisStatics["ATIS Krymsk"] = {}
Ugly.AtisStatics["ATIS Krymsk"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Krymsk"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Krymsk"]["y"] = 294748.625
Ugly.AtisStatics["ATIS Krymsk"]["x"] = -6770.953125
Ugly.AtisStatics["ATIS Krymsk"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Krymsk"]["heading"] = 0.68067815815167
Ugly.AtisStatics["ATIS Krymsk"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Krymsk"]["name"] = "ATIS Krymsk"
Ugly.AtisStatics["ATIS Krymsk"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Krymsk"]["dead"] = false
Ugly.AtisStatics["ATIS Kutaisi"] = {}
Ugly.AtisStatics["ATIS Kutaisi"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kutaisi"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kutaisi"]["y"] = 682961.1875
Ugly.AtisStatics["ATIS Kutaisi"]["x"] = -284446.6875
Ugly.AtisStatics["ATIS Kutaisi"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kutaisi"]["heading"] = 3.9269908169872
Ugly.AtisStatics["ATIS Kutaisi"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kutaisi"]["name"] = "ATIS Kutaisi"
Ugly.AtisStatics["ATIS Kutaisi"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kutaisi"]["dead"] = false
Ugly.AtisStatics["ATIS Mineralnye Vody"] = {}
Ugly.AtisStatics["ATIS Mineralnye Vody"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Mineralnye Vody"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Mineralnye Vody"]["y"] = 706277.625
Ugly.AtisStatics["ATIS Mineralnye Vody"]["x"] = -52001.62890625
Ugly.AtisStatics["ATIS Mineralnye Vody"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Mineralnye Vody"]["heading"] = 0.4363324999791
Ugly.AtisStatics["ATIS Mineralnye Vody"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Mineralnye Vody"]["name"] = "ATIS Mineralnye Vody"
Ugly.AtisStatics["ATIS Mineralnye Vody"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Mineralnye Vody"]["dead"] = false
Ugly.AtisStatics["ATIS Beslan"] = {}
Ugly.AtisStatics["ATIS Beslan"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Beslan"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Beslan"]["y"] = 843628.6875
Ugly.AtisStatics["ATIS Beslan"]["x"] = -148936.890625
Ugly.AtisStatics["ATIS Beslan"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Beslan"]["heading"] = 0.087266268117616
Ugly.AtisStatics["ATIS Beslan"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Beslan"]["name"] = "ATIS Beslan"
Ugly.AtisStatics["ATIS Beslan"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Beslan"]["dead"] = false
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"] = {}
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["y"] = 386457
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["x"] = 8007.7783203125
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["heading"] = 3.8048177655381
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["name"] = "ATIS Krasnodar-Pashkovsky"
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Krasnodar-Pashkovsky"]["dead"] = false
Ugly.AtisStatics["ATIS Tbilisi-Lochini"] = {}
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["y"] = 896497.125
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["x"] = -314656.75
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["heading"] = 3.6826446554276
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["name"] = "ATIS Tbilisi-Lochini"
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tbilisi-Lochini"]["dead"] = false
Ugly.AtisStatics["ATIS Khasab"] = {}  ---PG
Ugly.AtisStatics["ATIS Khasab"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Khasab"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Khasab"]["y"] = -463.55447387695
Ugly.AtisStatics["ATIS Khasab"]["x"] = -505.99624633789
Ugly.AtisStatics["ATIS Khasab"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Khasab"]["heading"] = 1.7974785084196
Ugly.AtisStatics["ATIS Khasab"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Khasab"]["name"] = "ATIS Khasab"
Ugly.AtisStatics["ATIS Khasab"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Khasab"]["dead"] = false
Ugly.AtisStatics["ATIS Fujairah Intl1"] = {}
Ugly.AtisStatics["ATIS Fujairah Intl1"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Fujairah Intl1"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Fujairah Intl1"]["y"] = 9001.1533203125
Ugly.AtisStatics["ATIS Fujairah Intl1"]["x"] = -117706.46875
Ugly.AtisStatics["ATIS Fujairah Intl1"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Fujairah Intl1"]["heading"] = 2.0071184895279
Ugly.AtisStatics["ATIS Fujairah Intl1"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Fujairah Intl1"]["name"] = "ATIS Fujairah Intl1"
Ugly.AtisStatics["ATIS Fujairah Intl1"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Fujairah Intl1"]["dead"] = false
Ugly.AtisStatics["ATIS Liwa AFB"] = {}
Ugly.AtisStatics["ATIS Liwa AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Liwa AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Liwa AFB"]["y"] = -248385.046875
Ugly.AtisStatics["ATIS Liwa AFB"]["x"] = -276166.4375
Ugly.AtisStatics["ATIS Liwa AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Liwa AFB"]["heading"] = 0.68067815815167
Ugly.AtisStatics["ATIS Liwa AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Liwa AFB"]["name"] = "ATIS Liwa AFB"
Ugly.AtisStatics["ATIS Liwa AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Liwa AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Al-Bateen"] = {}
Ugly.AtisStatics["ATIS Al-Bateen"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al-Bateen"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al-Bateen"]["y"] = -182632.09375
Ugly.AtisStatics["ATIS Al-Bateen"]["x"] = -190850.3125
Ugly.AtisStatics["ATIS Al-Bateen"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al-Bateen"]["heading"] = 2.2514746526723
Ugly.AtisStatics["ATIS Al-Bateen"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al-Bateen"]["name"] = "ATIS Al-Bateen"
Ugly.AtisStatics["ATIS Al-Bateen"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al-Bateen"]["dead"] = false
Ugly.AtisStatics["ATIS Qeshm Island"] = {}
Ugly.AtisStatics["ATIS Qeshm Island"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Qeshm Island"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Qeshm Island"]["y"] = -33047.28125
Ugly.AtisStatics["ATIS Qeshm Island"]["x"] = 65732.5390625
Ugly.AtisStatics["ATIS Qeshm Island"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Qeshm Island"]["heading"] = 3.316046850378
Ugly.AtisStatics["ATIS Qeshm Island"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Qeshm Island"]["name"] = "ATIS Qeshm Island"
Ugly.AtisStatics["ATIS Qeshm Island"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Qeshm Island"]["dead"] = false
Ugly.AtisStatics["ATIS Sas Al Nakheel"] = {}
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["y"] = -175540.90625
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["x"] = -190454.53125
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["heading"] = 6.0039324349187
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["name"] = "ATIS Sas Al Nakheel"
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sas Al Nakheel"]["dead"] = false
Ugly.AtisStatics["ATIS Sirri Island"] = {}
Ugly.AtisStatics["ATIS Sirri Island"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sirri Island"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sirri Island"]["y"] = -169809.71875
Ugly.AtisStatics["ATIS Sirri Island"]["x"] = -27921.30859375
Ugly.AtisStatics["ATIS Sirri Island"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sirri Island"]["heading"] = 0.69810228984512
Ugly.AtisStatics["ATIS Sirri Island"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sirri Island"]["name"] = "ATIS Sirri Island"
Ugly.AtisStatics["ATIS Sirri Island"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sirri Island"]["dead"] = false
Ugly.AtisStatics["ATIS Tunb Kochak"] = {}
Ugly.AtisStatics["ATIS Tunb Kochak"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tunb Kochak"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tunb Kochak"]["y"] = -109303.6328125
Ugly.AtisStatics["ATIS Tunb Kochak"]["x"] = 9002.734375
Ugly.AtisStatics["ATIS Tunb Kochak"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tunb Kochak"]["heading"] = 5.9864792716931
Ugly.AtisStatics["ATIS Tunb Kochak"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tunb Kochak"]["name"] = "ATIS Tunb Kochak"
Ugly.AtisStatics["ATIS Tunb Kochak"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tunb Kochak"]["dead"] = false
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"] = {}
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["y"] = -30729.232421875
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["x"] = -60837.3828125
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["heading"] = 2.9321532895007
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["name"] = "ATIS Ras Al Khaimah Intl"
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Ras Al Khaimah Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Kerman"] = {}
Ugly.AtisStatics["ATIS Kerman"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kerman"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kerman"]["y"] = 71954.8984375
Ugly.AtisStatics["ATIS Kerman"]["x"] = 454022.84375
Ugly.AtisStatics["ATIS Kerman"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kerman"]["heading"] = 3.6128316469267
Ugly.AtisStatics["ATIS Kerman"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kerman"]["name"] = "ATIS Kerman"
Ugly.AtisStatics["ATIS Kerman"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kerman"]["dead"] = false
Ugly.AtisStatics["ATIS Abu Musa Island"] = {}
Ugly.AtisStatics["ATIS Abu Musa Island"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu Musa Island"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Abu Musa Island"]["y"] = -121885.7265625
Ugly.AtisStatics["ATIS Abu Musa Island"]["x"] = -31316.880859375
Ugly.AtisStatics["ATIS Abu Musa Island"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Abu Musa Island"]["heading"] = 4.6774825493672
Ugly.AtisStatics["ATIS Abu Musa Island"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu Musa Island"]["name"] = "ATIS Abu Musa Island"
Ugly.AtisStatics["ATIS Abu Musa Island"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Abu Musa Island"]["dead"] = false
Ugly.AtisStatics["ATIS Tunb Island AFB"] = {}
Ugly.AtisStatics["ATIS Tunb Island AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tunb Island AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tunb Island AFB"]["y"] = -92696.96875
Ugly.AtisStatics["ATIS Tunb Island AFB"]["x"] = 10241.896484375
Ugly.AtisStatics["ATIS Tunb Island AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tunb Island AFB"]["heading"] = 0.52359896114991
Ugly.AtisStatics["ATIS Tunb Island AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tunb Island AFB"]["name"] = "ATIS Tunb Island AFB"
Ugly.AtisStatics["ATIS Tunb Island AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tunb Island AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Kish Intl"] = {}
Ugly.AtisStatics["ATIS Kish Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kish Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kish Intl"]["y"] = -224943.328125
Ugly.AtisStatics["ATIS Kish Intl"]["x"] = 43153.81640625
Ugly.AtisStatics["ATIS Kish Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kish Intl"]["heading"] = 3.2276978045644
Ugly.AtisStatics["ATIS Kish Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kish Intl"]["name"] = "ATIS Kish Intl"
Ugly.AtisStatics["ATIS Kish Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kish Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Havadarya"] = {}
Ugly.AtisStatics["ATIS Havadarya"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Havadarya"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Havadarya"]["y"] = -7060.2290039063
Ugly.AtisStatics["ATIS Havadarya"]["x"] = 108938.6640625
Ugly.AtisStatics["ATIS Havadarya"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Havadarya"]["heading"] = 6.2831198714595
Ugly.AtisStatics["ATIS Havadarya"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Havadarya"]["name"] = "ATIS Havadarya"
Ugly.AtisStatics["ATIS Havadarya"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Havadarya"]["dead"] = false
Ugly.AtisStatics["ATIS Al Minhad AFB"] = {}
Ugly.AtisStatics["ATIS Al Minhad AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Minhad AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al Minhad AFB"]["y"] = -87881.5546875
Ugly.AtisStatics["ATIS Al Minhad AFB"]["x"] = -126408.3828125
Ugly.AtisStatics["ATIS Al Minhad AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al Minhad AFB"]["heading"] = 4.1699523230349e-05
Ugly.AtisStatics["ATIS Al Minhad AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Minhad AFB"]["name"] = "ATIS Al Minhad AFB"
Ugly.AtisStatics["ATIS Al Minhad AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al Minhad AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Sir Abu Nuayr"] = {}
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["y"] = -203075.765625
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["x"] = -103056.15625
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["heading"] = 3.3161256972962
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["name"] = "ATIS Sir Abu Nuayr"
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sir Abu Nuayr"]["dead"] = false
Ugly.AtisStatics["ATIS Al Ain Intl"] = {}
Ugly.AtisStatics["ATIS Al Ain Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Ain Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al Ain Intl"]["y"] = -64730.59765625
Ugly.AtisStatics["ATIS Al Ain Intl"]["x"] = -209183.921875
Ugly.AtisStatics["ATIS Al Ain Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al Ain Intl"]["heading"] = 0
Ugly.AtisStatics["ATIS Al Ain Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Ain Intl"]["name"] = "ATIS Al Ain Intl"
Ugly.AtisStatics["ATIS Al Ain Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al Ain Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Dubai Intl"] = {}
Ugly.AtisStatics["ATIS Dubai Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Dubai Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Dubai Intl"]["y"] = -90677.0390625
Ugly.AtisStatics["ATIS Dubai Intl"]["x"] = -100323.2109375
Ugly.AtisStatics["ATIS Dubai Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Dubai Intl"]["heading"] = 0.54105213476778
Ugly.AtisStatics["ATIS Dubai Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Dubai Intl"]["name"] = "ATIS Dubai Intl"
Ugly.AtisStatics["ATIS Dubai Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Dubai Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Bandar Lengeh"] = {}
Ugly.AtisStatics["ATIS Bandar Lengeh"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar Lengeh"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Bandar Lengeh"]["y"] = -140514.171875
Ugly.AtisStatics["ATIS Bandar Lengeh"]["x"] = 41333.52734375
Ugly.AtisStatics["ATIS Bandar Lengeh"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Bandar Lengeh"]["heading"] = 6.1261057857694
Ugly.AtisStatics["ATIS Bandar Lengeh"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar Lengeh"]["name"] = "ATIS Bandar Lengeh"
Ugly.AtisStatics["ATIS Bandar Lengeh"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Bandar Lengeh"]["dead"] = false
Ugly.AtisStatics["ATIS Bandar-e-Jask"] = {}
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["y"] = 154940
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["x"] = -57594.44140625
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["heading"] = 1.9719691152318
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["name"] = "ATIS Bandar-e-Jask"
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Bandar-e-Jask"]["dead"] = false
Ugly.AtisStatics["ATIS Bandar Abbas Intl"] = {}
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["y"] = 13477.2265625
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["x"] = 115189.0390625
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["heading"] = 3.6127993078887
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["name"] = "ATIS Bandar Abbas Intl"
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Bandar Abbas Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Jiroft"] = {}
Ugly.AtisStatics["ATIS Jiroft"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Jiroft"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Jiroft"]["y"] = 141675.375
Ugly.AtisStatics["ATIS Jiroft"]["x"] = 283019.625
Ugly.AtisStatics["ATIS Jiroft"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Jiroft"]["heading"] = 3.8088024480253
Ugly.AtisStatics["ATIS Jiroft"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Jiroft"]["name"] = "ATIS Jiroft"
Ugly.AtisStatics["ATIS Jiroft"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Jiroft"]["dead"] = false
Ugly.AtisStatics["ATIS Al Maktoum Intl"] = {}
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["y"] = -108122.125
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["x"] = -141687.21875
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["heading"] = 0.48869211721105
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["name"] = "ATIS Al Maktoum Intl"
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al Maktoum Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Al Dhafra AFB"] = {}
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["y"] = -174232.484375
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["x"] = -209311.296875
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["heading"] = 5.4628806396425
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["name"] = "ATIS Al Dhafra AFB"
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al Dhafra AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Sharjah Intl"] = {}
Ugly.AtisStatics["ATIS Sharjah Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Sharjah Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Sharjah Intl"]["y"] = -74815.4765625
Ugly.AtisStatics["ATIS Sharjah Intl"]["x"] = -92524.7109375
Ugly.AtisStatics["ATIS Sharjah Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Sharjah Intl"]["heading"] = 5.2708946146115
Ugly.AtisStatics["ATIS Sharjah Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Sharjah Intl"]["name"] = "ATIS Sharjah Intl"
Ugly.AtisStatics["ATIS Sharjah Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Sharjah Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Lavan Island"] = {}
Ugly.AtisStatics["ATIS Lavan Island"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Lavan Island"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Lavan Island"]["y"] = -287456.09375
Ugly.AtisStatics["ATIS Lavan Island"]["x"] = 75728.8046875
Ugly.AtisStatics["ATIS Lavan Island"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Lavan Island"]["heading"] = 0.34906563190573
Ugly.AtisStatics["ATIS Lavan Island"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Lavan Island"]["name"] = "ATIS Lavan Island"
Ugly.AtisStatics["ATIS Lavan Island"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Lavan Island"]["dead"] = false
Ugly.AtisStatics["ATIS Shiraz Intl"] = {}
Ugly.AtisStatics["ATIS Shiraz Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Shiraz Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Shiraz Intl"]["y"] = -352967.25
Ugly.AtisStatics["ATIS Shiraz Intl"]["x"] = 382282.125
Ugly.AtisStatics["ATIS Shiraz Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Shiraz Intl"]["heading"] = 3.6302848777646
Ugly.AtisStatics["ATIS Shiraz Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Shiraz Intl"]["name"] = "ATIS Shiraz Intl"
Ugly.AtisStatics["ATIS Shiraz Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Shiraz Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Lar"] = {}
Ugly.AtisStatics["ATIS Lar"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Lar"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Lar"]["y"] = -182522.59375
Ugly.AtisStatics["ATIS Lar"]["x"] = 168489.34375
Ugly.AtisStatics["ATIS Lar"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Lar"]["heading"] = 1.57079631487
Ugly.AtisStatics["ATIS Lar"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Lar"]["name"] = "ATIS Lar"
Ugly.AtisStatics["ATIS Lar"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Lar"]["dead"] = false
Ugly.AtisStatics["ATIS Abu Dhabi Intl"] = {}
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["y"] = -163420.8125
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["x"] = -189042.71875
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["heading"] = 5.7421331724118
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["name"] = "ATIS Abu Dhabi Intl"
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Abu Dhabi Intl"]["dead"] = false
Ugly.AtisStatics["ATIS Eyn Shemer"] = {}  ---Syria
Ugly.AtisStatics["ATIS Eyn Shemer"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Eyn Shemer"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Eyn Shemer"]["y"] = -92593.5703125
Ugly.AtisStatics["ATIS Eyn Shemer"]["x"] = -283576.9375
Ugly.AtisStatics["ATIS Eyn Shemer"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Eyn Shemer"]["heading"] = 0.19187193830264
Ugly.AtisStatics["ATIS Eyn Shemer"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Eyn Shemer"]["name"] = "ATIS Eyn Shemer"
Ugly.AtisStatics["ATIS Eyn Shemer"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Eyn Shemer"]["dead"] = false
Ugly.AtisStatics["ATIS Marj as Sultan North"] = {}
Ugly.AtisStatics["ATIS Marj as Sultan North"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj as Sultan North"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Marj as Sultan North"]["y"] = 47512.19140625
Ugly.AtisStatics["ATIS Marj as Sultan North"]["x"] = -169970.59375
Ugly.AtisStatics["ATIS Marj as Sultan North"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Marj as Sultan North"]["heading"] = 3.420522376796
Ugly.AtisStatics["ATIS Marj as Sultan North"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj as Sultan North"]["name"] = "ATIS Marj as Sultan North"
Ugly.AtisStatics["ATIS Marj as Sultan North"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Marj as Sultan North"]["dead"] = false
Ugly.AtisStatics["ATIS Minakh"] = {}
Ugly.AtisStatics["ATIS Minakh"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Minakh"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Minakh"]["y"] = 107234.796875
Ugly.AtisStatics["ATIS Minakh"]["x"] = 163518.84375
Ugly.AtisStatics["ATIS Minakh"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Minakh"]["heading"] = 0
Ugly.AtisStatics["ATIS Minakh"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Minakh"]["name"] = "ATIS Minakh"
Ugly.AtisStatics["ATIS Minakh"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Minakh"]["dead"] = false
Ugly.AtisStatics["ATIS Al Qusayr"] = {}
Ugly.AtisStatics["ATIS Al Qusayr"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Qusayr"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al Qusayr"]["y"] = 61372.89453125
Ugly.AtisStatics["ATIS Al Qusayr"]["x"] = -52636.5859375
Ugly.AtisStatics["ATIS Al Qusayr"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al Qusayr"]["heading"] = 1.5358899292969
Ugly.AtisStatics["ATIS Al Qusayr"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al Qusayr"]["name"] = "ATIS Al Qusayr"
Ugly.AtisStatics["ATIS Al Qusayr"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al Qusayr"]["dead"] = false
Ugly.AtisStatics["ATIS Bassel Al-Assad"] = {}
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["y"] = 5115.2299804688
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["x"] = 42915.25390625
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["heading"] = 1.536078359291
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["name"] = "ATIS Bassel Al-Assad"
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Bassel Al-Assad"]["dead"] = false
Ugly.AtisStatics["ATIS Abu al-Duhur"] = {}
Ugly.AtisStatics["ATIS Abu al-Duhur"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu al-Duhur"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Abu al-Duhur"]["y"] = 112907.2734375
Ugly.AtisStatics["ATIS Abu al-Duhur"]["x"] = 76198.4453125
Ugly.AtisStatics["ATIS Abu al-Duhur"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Abu al-Duhur"]["heading"] = 0.052359886742702
Ugly.AtisStatics["ATIS Abu al-Duhur"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Abu al-Duhur"]["name"] = "ATIS Abu al-Duhur"
Ugly.AtisStatics["ATIS Abu al-Duhur"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Abu al-Duhur"]["dead"] = false
Ugly.AtisStatics["ATIS Ramat David"] = {}
Ugly.AtisStatics["ATIS Ramat David"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Ramat David"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Ramat David"]["y"] = -74850.5234375
Ugly.AtisStatics["ATIS Ramat David"]["x"] = -258819.21875
Ugly.AtisStatics["ATIS Ramat David"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Ramat David"]["heading"] = 0.3488051406753
Ugly.AtisStatics["ATIS Ramat David"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Ramat David"]["name"] = "ATIS Ramat David"
Ugly.AtisStatics["ATIS Ramat David"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Ramat David"]["dead"] = false
Ugly.AtisStatics["ATIS Megiddo"] = {}
Ugly.AtisStatics["ATIS Megiddo"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Megiddo"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Megiddo"]["y"] = -70515.890625
Ugly.AtisStatics["ATIS Megiddo"]["x"] = -267337.625
Ugly.AtisStatics["ATIS Megiddo"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Megiddo"]["heading"] = 1.0297444885971
Ugly.AtisStatics["ATIS Megiddo"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Megiddo"]["name"] = "ATIS Megiddo"
Ugly.AtisStatics["ATIS Megiddo"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Megiddo"]["dead"] = false
Ugly.AtisStatics["ATIS Rayak"] = {}
Ugly.AtisStatics["ATIS Rayak"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Rayak"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Rayak"]["y"] = 4621.9892578125
Ugly.AtisStatics["ATIS Rayak"]["x"] = -130044.890625
Ugly.AtisStatics["ATIS Rayak"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Rayak"]["heading"] = 5.5149402209806
Ugly.AtisStatics["ATIS Rayak"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Rayak"]["name"] = "ATIS Rayak"
Ugly.AtisStatics["ATIS Rayak"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Rayak"]["dead"] = false
Ugly.AtisStatics["ATIS Tabqa"] = {}
Ugly.AtisStatics["ATIS Tabqa"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tabqa"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tabqa"]["y"] = 244618.578125
Ugly.AtisStatics["ATIS Tabqa"]["x"] = 77263.4921875
Ugly.AtisStatics["ATIS Tabqa"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tabqa"]["heading"] = 3.1938433755542
Ugly.AtisStatics["ATIS Tabqa"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tabqa"]["name"] = "ATIS Tabqa"
Ugly.AtisStatics["ATIS Tabqa"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tabqa"]["dead"] = false
Ugly.AtisStatics["ATIS Aleppo"] = {}
Ugly.AtisStatics["ATIS Aleppo"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Aleppo"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Aleppo"]["y"] = 123138.6328125
Ugly.AtisStatics["ATIS Aleppo"]["x"] = 125979.890625
Ugly.AtisStatics["ATIS Aleppo"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Aleppo"]["heading"] = 3.3335788919752
Ugly.AtisStatics["ATIS Aleppo"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Aleppo"]["name"] = "ATIS Aleppo"
Ugly.AtisStatics["ATIS Aleppo"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Aleppo"]["dead"] = false
Ugly.AtisStatics["ATIS Palmyra"] = {}
Ugly.AtisStatics["ATIS Palmyra"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Palmyra"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Palmyra"]["y"] = 219837.640625
Ugly.AtisStatics["ATIS Palmyra"]["x"] = -55977.69921875
Ugly.AtisStatics["ATIS Palmyra"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Palmyra"]["heading"] = 6.1437447852141
Ugly.AtisStatics["ATIS Palmyra"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Palmyra"]["name"] = "ATIS Palmyra"
Ugly.AtisStatics["ATIS Palmyra"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Palmyra"]["dead"] = false
Ugly.AtisStatics["ATIS Damascus"] = {}
Ugly.AtisStatics["ATIS Damascus"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Damascus"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Damascus"]["y"] = 51510.41015625
Ugly.AtisStatics["ATIS Damascus"]["x"] = -181031.828125
Ugly.AtisStatics["ATIS Damascus"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Damascus"]["heading"] = 0.89011795457893
Ugly.AtisStatics["ATIS Damascus"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Damascus"]["name"] = "ATIS Damascus"
Ugly.AtisStatics["ATIS Damascus"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Damascus"]["dead"] = false
Ugly.AtisStatics["ATIS Wujah Al Hajar"] = {}
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["y"] = -22907.873046875
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["x"] = -81336.203125
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["heading"] = 0.66335778529643
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["name"] = "ATIS Wujah Al Hajar"
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Wujah Al Hajar"]["dead"] = false
Ugly.AtisStatics["ATIS Incirlik"] = {}
Ugly.AtisStatics["ATIS Incirlik"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Incirlik"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Incirlik"]["y"] = -35242.68359375
Ugly.AtisStatics["ATIS Incirlik"]["x"] = 220498.8125
Ugly.AtisStatics["ATIS Incirlik"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Incirlik"]["heading"] = 5.6546382967056
Ugly.AtisStatics["ATIS Incirlik"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Incirlik"]["name"] = "ATIS Incirlik"
Ugly.AtisStatics["ATIS Incirlik"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Incirlik"]["dead"] = false
Ugly.AtisStatics["ATIS Qabr as Sitt"] = {}
Ugly.AtisStatics["ATIS Qabr as Sitt"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Qabr as Sitt"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Qabr as Sitt"]["y"] = 36845.42578125
Ugly.AtisStatics["ATIS Qabr as Sitt"]["x"] = -174585.828125
Ugly.AtisStatics["ATIS Qabr as Sitt"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Qabr as Sitt"]["heading"] = 2.8623457557545
Ugly.AtisStatics["ATIS Qabr as Sitt"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Qabr as Sitt"]["name"] = "ATIS Qabr as Sitt"
Ugly.AtisStatics["ATIS Qabr as Sitt"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Qabr as Sitt"]["dead"] = false
Ugly.AtisStatics["ATIS Khalkhalah"] = {}
Ugly.AtisStatics["ATIS Khalkhalah"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Khalkhalah"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Khalkhalah"]["y"] = 53908.9609375
Ugly.AtisStatics["ATIS Khalkhalah"]["x"] = -217893.0625
Ugly.AtisStatics["ATIS Khalkhalah"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Khalkhalah"]["heading"] = 2.6005444229584
Ugly.AtisStatics["ATIS Khalkhalah"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Khalkhalah"]["name"] = "ATIS Khalkhalah"
Ugly.AtisStatics["ATIS Khalkhalah"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Khalkhalah"]["dead"] = false
Ugly.AtisStatics["ATIS An Nasiriyah"] = {}
Ugly.AtisStatics["ATIS An Nasiriyah"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS An Nasiriyah"]["CountryID"] = 2
Ugly.AtisStatics["ATIS An Nasiriyah"]["y"] = 85961.5546875
Ugly.AtisStatics["ATIS An Nasiriyah"]["x"] = -123461.1796875
Ugly.AtisStatics["ATIS An Nasiriyah"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS An Nasiriyah"]["heading"] = 0.92520967848089
Ugly.AtisStatics["ATIS An Nasiriyah"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS An Nasiriyah"]["name"] = "ATIS An Nasiriyah"
Ugly.AtisStatics["ATIS An Nasiriyah"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS An Nasiriyah"]["dead"] = false
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"] = {}
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["y"] = -41900.05859375
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["x"] = -131084.421875
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["heading"] = 4.6425756836651
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["name"] = "ATIS Beirut-Rafic Hariri"
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Beirut-Rafic Hariri"]["dead"] = false
Ugly.AtisStatics["ATIS Hatay"] = {}
Ugly.AtisStatics["ATIS Hatay"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Hatay"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Hatay"]["y"] = 38783.62890625
Ugly.AtisStatics["ATIS Hatay"]["x"] = 147667.140625
Ugly.AtisStatics["ATIS Hatay"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Hatay"]["heading"] = 2.3911158337648
Ugly.AtisStatics["ATIS Hatay"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Hatay"]["name"] = "ATIS Hatay"
Ugly.AtisStatics["ATIS Hatay"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Hatay"]["dead"] = false
Ugly.AtisStatics["ATIS King Hussein Air College"] = {}
Ugly.AtisStatics["ATIS King Hussein Air College"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS King Hussein Air College"]["CountryID"] = 2
Ugly.AtisStatics["ATIS King Hussein Air College"]["y"] = 24275.162109375
Ugly.AtisStatics["ATIS King Hussein Air College"]["x"] = -295242.4375
Ugly.AtisStatics["ATIS King Hussein Air College"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS King Hussein Air College"]["heading"] = 3.7873645371225
Ugly.AtisStatics["ATIS King Hussein Air College"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS King Hussein Air College"]["name"] = "ATIS King Hussein Air College"
Ugly.AtisStatics["ATIS King Hussein Air College"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS King Hussein Air College"]["dead"] = false
Ugly.AtisStatics["ATIS Rene Mouawad"] = {}
Ugly.AtisStatics["ATIS Rene Mouawad"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Rene Mouawad"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Rene Mouawad"]["y"] = 8537.21875
Ugly.AtisStatics["ATIS Rene Mouawad"]["x"] = -47984.59375
Ugly.AtisStatics["ATIS Rene Mouawad"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Rene Mouawad"]["heading"] = 2.6354473322669
Ugly.AtisStatics["ATIS Rene Mouawad"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Rene Mouawad"]["name"] = "ATIS Rene Mouawad"
Ugly.AtisStatics["ATIS Rene Mouawad"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Rene Mouawad"]["dead"] = false
Ugly.AtisStatics["ATIS Al-Dumayr"] = {}
Ugly.AtisStatics["ATIS Al-Dumayr"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Al-Dumayr"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Al-Dumayr"]["y"] = 73980.421875
Ugly.AtisStatics["ATIS Al-Dumayr"]["x"] = -158128.75
Ugly.AtisStatics["ATIS Al-Dumayr"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Al-Dumayr"]["heading"] = 2.6703537138866
Ugly.AtisStatics["ATIS Al-Dumayr"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Al-Dumayr"]["name"] = "ATIS Al-Dumayr"
Ugly.AtisStatics["ATIS Al-Dumayr"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Al-Dumayr"]["dead"] = false
Ugly.AtisStatics["ATIS Adana Sakirpasa"] = {}
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["y"] = -47472.37109375
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["x"] = 219514.53125
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["heading"] = 0.1745327103881
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["name"] = "ATIS Adana Sakirpasa"
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Adana Sakirpasa"]["dead"] = false
Ugly.AtisStatics["ATIS Kuweires"] = {}
Ugly.AtisStatics["ATIS Kuweires"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kuweires"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kuweires"]["y"] = 154797.109375
Ugly.AtisStatics["ATIS Kuweires"]["x"] = 125325.4296875
Ugly.AtisStatics["ATIS Kuweires"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kuweires"]["heading"] = 0.19198638471316
Ugly.AtisStatics["ATIS Kuweires"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kuweires"]["name"] = "ATIS Kuweires"
Ugly.AtisStatics["ATIS Kuweires"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kuweires"]["dead"] = false
Ugly.AtisStatics["ATIS Taftanaz"] = {}
Ugly.AtisStatics["ATIS Taftanaz"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Taftanaz"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Taftanaz"]["y"] = 82940.7421875
Ugly.AtisStatics["ATIS Taftanaz"]["x"] = 103798.0859375
Ugly.AtisStatics["ATIS Taftanaz"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Taftanaz"]["heading"] = 3.420845337465
Ugly.AtisStatics["ATIS Taftanaz"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Taftanaz"]["name"] = "ATIS Taftanaz"
Ugly.AtisStatics["ATIS Taftanaz"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Taftanaz"]["dead"] = false
Ugly.AtisStatics["ATIS Marj as Sultan South"] = {}
Ugly.AtisStatics["ATIS Marj as Sultan South"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj as Sultan South"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Marj as Sultan South"]["y"] = 48059.9296875
Ugly.AtisStatics["ATIS Marj as Sultan South"]["x"] = -171793.140625
Ugly.AtisStatics["ATIS Marj as Sultan South"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Marj as Sultan South"]["heading"] = 1.5883580137075
Ugly.AtisStatics["ATIS Marj as Sultan South"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj as Sultan South"]["name"] = "ATIS Marj as Sultan South"
Ugly.AtisStatics["ATIS Marj as Sultan South"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Marj as Sultan South"]["dead"] = false
Ugly.AtisStatics["ATIS Mezzeh"] = {}
Ugly.AtisStatics["ATIS Mezzeh"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Mezzeh"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Mezzeh"]["y"] = 24431.068359375
Ugly.AtisStatics["ATIS Mezzeh"]["x"] = -172015.84375
Ugly.AtisStatics["ATIS Mezzeh"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Mezzeh"]["heading"] = 2.6003416815269
Ugly.AtisStatics["ATIS Mezzeh"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Mezzeh"]["name"] = "ATIS Mezzeh"
Ugly.AtisStatics["ATIS Mezzeh"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Mezzeh"]["dead"] = false
Ugly.AtisStatics["ATIS Haifa"] = {}
Ugly.AtisStatics["ATIS Haifa"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Haifa"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Haifa"]["y"] = -87774.9453125
Ugly.AtisStatics["ATIS Haifa"]["x"] = -242884.625
Ugly.AtisStatics["ATIS Haifa"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Haifa"]["heading"] = 1.291543802647
Ugly.AtisStatics["ATIS Haifa"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Haifa"]["name"] = "ATIS Haifa"
Ugly.AtisStatics["ATIS Haifa"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Haifa"]["dead"] = false
Ugly.AtisStatics["ATIS Marj Ruhayyil"] = {}
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["y"] = 45971.4921875
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["x"] = -193030.84375
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["heading"] = 1.7622398794294
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["name"] = "ATIS Marj Ruhayyil"
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Marj Ruhayyil"]["dead"] = false
Ugly.AtisStatics["ATIS Kiryat Shmona"] = {}
Ugly.AtisStatics["ATIS Kiryat Shmona"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Kiryat Shmona"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Kiryat Shmona"]["y"] = -35372.94921875
Ugly.AtisStatics["ATIS Kiryat Shmona"]["x"] = -199940.109375
Ugly.AtisStatics["ATIS Kiryat Shmona"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Kiryat Shmona"]["heading"] = 2.6703537138866
Ugly.AtisStatics["ATIS Kiryat Shmona"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Kiryat Shmona"]["name"] = "ATIS Kiryat Shmona"
Ugly.AtisStatics["ATIS Kiryat Shmona"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Kiryat Shmona"]["dead"] = false
Ugly.AtisStatics["ATIS Jirah"] = {}
Ugly.AtisStatics["ATIS Jirah"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Jirah"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Jirah"]["y"] = 188539.140625
Ugly.AtisStatics["ATIS Jirah"]["x"] = 115190.3984375
Ugly.AtisStatics["ATIS Jirah"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Jirah"]["heading"] = 0.19189057387965
Ugly.AtisStatics["ATIS Jirah"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Jirah"]["name"] = "ATIS Jirah"
Ugly.AtisStatics["ATIS Jirah"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Jirah"]["dead"] = false
Ugly.AtisStatics["ATIS Hama"] = {}
Ugly.AtisStatics["ATIS Hama"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Hama"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Hama"]["y"] = 73964.890625
Ugly.AtisStatics["ATIS Hama"]["x"] = 9171.4091796875
Ugly.AtisStatics["ATIS Hama"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Hama"]["heading"] = 2.7227137565031
Ugly.AtisStatics["ATIS Hama"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Hama"]["name"] = "ATIS Hama"
Ugly.AtisStatics["ATIS Hama"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Hama"]["dead"] = false
Ugly.AtisStatics["ATIS Creech AFB"] = {}  ---Nevada
Ugly.AtisStatics["ATIS Creech AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Creech AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Creech AFB"]["y"] = -75144.6640625
Ugly.AtisStatics["ATIS Creech AFB"]["x"] = -360826.75
Ugly.AtisStatics["ATIS Creech AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Creech AFB"]["heading"] = 0.034906688000728
Ugly.AtisStatics["ATIS Creech AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Creech AFB"]["name"] = "ATIS Creech AFB"
Ugly.AtisStatics["ATIS Creech AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Creech AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Beatty Airport"] = {}
Ugly.AtisStatics["ATIS Beatty Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Beatty Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Beatty Airport"]["y"] = -174819.171875
Ugly.AtisStatics["ATIS Beatty Airport"]["x"] = -329773.125
Ugly.AtisStatics["ATIS Beatty Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Beatty Airport"]["heading"] = 6.283068830042
Ugly.AtisStatics["ATIS Beatty Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Beatty Airport"]["name"] = "ATIS Beatty Airport"
Ugly.AtisStatics["ATIS Beatty Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Beatty Airport"]["dead"] = false
Ugly.AtisStatics["ATIS North Las Vegas"] = {}
Ugly.AtisStatics["ATIS North Las Vegas"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS North Las Vegas"]["CountryID"] = 2
Ugly.AtisStatics["ATIS North Las Vegas"]["y"] = -31006.939453125
Ugly.AtisStatics["ATIS North Las Vegas"]["x"] = -401114.6875
Ugly.AtisStatics["ATIS North Las Vegas"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS North Las Vegas"]["heading"] = 4.6600288777917
Ugly.AtisStatics["ATIS North Las Vegas"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS North Las Vegas"]["name"] = "ATIS North Las Vegas"
Ugly.AtisStatics["ATIS North Las Vegas"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS North Las Vegas"]["dead"] = false
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"] = {}
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["y"] = -174118.171875
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["x"] = -226227.140625
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["heading"] = 4.345870102994
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["name"] = "ATIS Tonopah Test Range Airfield"
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tonopah Test Range Airfield"]["dead"] = false
Ugly.AtisStatics["ATIS Boulder City Airport"] = {}
Ugly.AtisStatics["ATIS Boulder City Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Boulder City Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Boulder City Airport"]["y"] = -690.23468017578
Ugly.AtisStatics["ATIS Boulder City Airport"]["x"] = -429615.375
Ugly.AtisStatics["ATIS Boulder City Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Boulder City Airport"]["heading"] = 3.2637217638999
Ugly.AtisStatics["ATIS Boulder City Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Boulder City Airport"]["name"] = "ATIS Boulder City Airport"
Ugly.AtisStatics["ATIS Boulder City Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Boulder City Airport"]["dead"] = false
Ugly.AtisStatics["ATIS Henderson Executive Airport"] = {}
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["y"] = -26202.18359375
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["x"] = -427089.90625
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["heading"] = 1.5707261589031
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["name"] = "ATIS Henderson Executive Airport"
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Henderson Executive Airport"]["dead"] = false
Ugly.AtisStatics["ATIS Lincoln County"] = {}
Ugly.AtisStatics["ATIS Lincoln County"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Lincoln County"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Lincoln County"]["y"] = 33358.01171875
Ugly.AtisStatics["ATIS Lincoln County"]["x"] = -224245.25
Ugly.AtisStatics["ATIS Lincoln County"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Lincoln County"]["heading"] = 0
Ugly.AtisStatics["ATIS Lincoln County"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Lincoln County"]["name"] = "ATIS Lincoln County"
Ugly.AtisStatics["ATIS Lincoln County"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Lincoln County"]["dead"] = false
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"] = {}
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["y"] = -132990.359375
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["x"] = -303460.09375
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["heading"] = 3.3335788919752
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["name"] = "ATIS Pahute Mesa Airstrip"
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Pahute Mesa Airstrip"]["dead"] = false
Ugly.AtisStatics["ATIS Mesquite"] = {}
Ugly.AtisStatics["ATIS Mesquite"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Mesquite"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Mesquite"]["y"] = 68339.1328125
Ugly.AtisStatics["ATIS Mesquite"]["x"] = -329787.46875
Ugly.AtisStatics["ATIS Mesquite"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Mesquite"]["heading"] = 2.0420353998234
Ugly.AtisStatics["ATIS Mesquite"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Mesquite"]["name"] = "ATIS Mesquite"
Ugly.AtisStatics["ATIS Mesquite"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Mesquite"]["dead"] = false
Ugly.AtisStatics["ATIS Echo Bay"] = {}
Ugly.AtisStatics["ATIS Echo Bay"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Echo Bay"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Echo Bay"]["y"] = 33624.1484375
Ugly.AtisStatics["ATIS Echo Bay"]["x"] = -388543.5
Ugly.AtisStatics["ATIS Echo Bay"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Echo Bay"]["heading"] = 3.420460623074
Ugly.AtisStatics["ATIS Echo Bay"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Echo Bay"]["name"] = "ATIS Echo Bay"
Ugly.AtisStatics["ATIS Echo Bay"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Echo Bay"]["dead"] = false
Ugly.AtisStatics["ATIS McCarran International Airport"] = {}
Ugly.AtisStatics["ATIS McCarran International Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS McCarran International Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS McCarran International Airport"]["y"] = -26912.173828125
Ugly.AtisStatics["ATIS McCarran International Airport"]["x"] = -415480.65625
Ugly.AtisStatics["ATIS McCarran International Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS McCarran International Airport"]["heading"] = 4.4344229184584
Ugly.AtisStatics["ATIS McCarran International Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS McCarran International Airport"]["name"] = "ATIS McCarran International Airport"
Ugly.AtisStatics["ATIS McCarran International Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS McCarran International Airport"]["dead"] = false
Ugly.AtisStatics["ATIS Nellis AFB"] = {}
Ugly.AtisStatics["ATIS Nellis AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Nellis AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Nellis AFB"]["y"] = -17124.751953125
Ugly.AtisStatics["ATIS Nellis AFB"]["x"] = -396616.625
Ugly.AtisStatics["ATIS Nellis AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Nellis AFB"]["heading"] = 6.283162673753
Ugly.AtisStatics["ATIS Nellis AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Nellis AFB"]["name"] = "ATIS Nellis AFB"
Ugly.AtisStatics["ATIS Nellis AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Nellis AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Groom Lake AFB"] = {}
Ugly.AtisStatics["ATIS Groom Lake AFB"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Groom Lake AFB"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Groom Lake AFB"]["y"] = -88856.265625
Ugly.AtisStatics["ATIS Groom Lake AFB"]["x"] = -288548.03125
Ugly.AtisStatics["ATIS Groom Lake AFB"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Groom Lake AFB"]["heading"] = 1.500930113699
Ugly.AtisStatics["ATIS Groom Lake AFB"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Groom Lake AFB"]["name"] = "ATIS Groom Lake AFB"
Ugly.AtisStatics["ATIS Groom Lake AFB"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Groom Lake AFB"]["dead"] = false
Ugly.AtisStatics["ATIS Tonopah Airport"] = {}
Ugly.AtisStatics["ATIS Tonopah Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Tonopah Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Tonopah Airport"]["y"] = -202422.75
Ugly.AtisStatics["ATIS Tonopah Airport"]["x"] = -197205.515625
Ugly.AtisStatics["ATIS Tonopah Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Tonopah Airport"]["heading"] = 2.0420353998234
Ugly.AtisStatics["ATIS Tonopah Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Tonopah Airport"]["name"] = "ATIS Tonopah Airport"
Ugly.AtisStatics["ATIS Tonopah Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Tonopah Airport"]["dead"] = false
Ugly.AtisStatics["ATIS Laughlin Airport"] = {}
Ugly.AtisStatics["ATIS Laughlin Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Laughlin Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Laughlin Airport"]["y"] = 28445.501953125
Ugly.AtisStatics["ATIS Laughlin Airport"]["x"] = -516316.25
Ugly.AtisStatics["ATIS Laughlin Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Laughlin Airport"]["heading"] = 6.2133722376745
Ugly.AtisStatics["ATIS Laughlin Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Laughlin Airport"]["name"] = "ATIS Laughlin Airport"
Ugly.AtisStatics["ATIS Laughlin Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Laughlin Airport"]["dead"] = false
Ugly.AtisStatics["ATIS Mina Airport 3Q0"] = {}
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["y"] = -290250.65625
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["x"] = -160899.25
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["heading"] = 2.0414938150212
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["name"] = "ATIS Mina Airport 3Q0"
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Mina Airport 3Q0"]["dead"] = false
Ugly.AtisStatics["ATIS Jean Airport"] = {}
Ugly.AtisStatics["ATIS Jean Airport"]["shape_name"] = "UH-1H"
Ugly.AtisStatics["ATIS Jean Airport"]["CountryID"] = 2
Ugly.AtisStatics["ATIS Jean Airport"]["y"] = -43028.15625
Ugly.AtisStatics["ATIS Jean Airport"]["x"] = -450145.09375
Ugly.AtisStatics["ATIS Jean Airport"]["CategoryID"] = 3
Ugly.AtisStatics["ATIS Jean Airport"]["heading"] = 2.1118481649927
Ugly.AtisStatics["ATIS Jean Airport"]["type"] = "UH-1H"
Ugly.AtisStatics["ATIS Jean Airport"]["name"] = "ATIS Jean Airport"
Ugly.AtisStatics["ATIS Jean Airport"]["CoalitionID"] = 2
Ugly.AtisStatics["ATIS Jean Airport"]["dead"] = false
